// web/src/features/config-center/enums/EnumsPanel.tsx
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Form, Input, Modal, Table, Tooltip } from 'antd'
import { useState } from 'react'

import { createEnum, deleteEnum, updateEnum } from '@/api/enums'
import { getApiErrorMessage } from '@/api/errors'
import type { Identifier } from '@/api/types'
import { queryKeys } from '@/app/query-keys'
import { useEnvironment } from '@/auth/environment-state'
import { requireEnumValues } from '../editor-validation'
import { type ConfigEnum, type ConfigEnumValue, useEnumsQuery } from '../queries'

type EnumForm = { key: string; name: string; description: string; values: ConfigEnumValue[] }
type Props = { projectId: Identifier; configId: Identifier; onChanged?: () => void }

const emptyValue = (): ConfigEnumValue => ({ label: '', value: '', description: '' })

export default function EnumsPanel({ projectId, configId, onChanged }: Props) {
  const { message, modal } = App.useApp()
  const environment = useEnvironment()
  const queryClient = useQueryClient()
  const enums = useEnumsQuery(environment.currentId, projectId, configId)
  const canWrite = environment.hasPermission('enum:write')
  const [form] = Form.useForm<EnumForm>()
  const [editing, setEditing] = useState<ConfigEnum | null>(null)
  const [open, setOpen] = useState(false)
  const [actionError, setActionError] = useState<unknown>(null)
  const refresh = () => environment.currentId === null ? Promise.resolve() : queryClient.invalidateQueries({ queryKey: queryKeys.enums(environment.currentId, projectId, configId) })
  const save = useMutation({
    mutationFn: (values: EnumForm) => {
      if (environment.currentId === null) throw new Error('当前没有可用环境')
      requireEnumValues(values.values)
      const request = { key: values.key, name: values.name, description: values.description, values: values.values }
      return editing ? updateEnum(environment.currentId, { ...request, id: editing.id, version: editing.version }) : createEnum(environment.currentId, { ...request, config_id: configId })
    },
    onSuccess: refresh,
  })
  const remove = useMutation({
    mutationFn: (id: Identifier) => { if (environment.currentId === null) throw new Error('当前没有可用环境'); return deleteEnum(environment.currentId, id) },
    onSuccess: refresh,
  })
  const close = () => { setOpen(false); setEditing(null); form.resetFields() }
  const showCreate = () => { setActionError(null); setEditing(null); form.setFieldsValue({ key: '', name: '', description: '', values: [emptyValue()] }); setOpen(true) }
  const showEdit = (item: ConfigEnum) => { setActionError(null); setEditing(item); form.setFieldsValue({ key: item.key, name: item.name, description: item.description ?? '', values: item.values.map((value) => ({ ...value })) }); setOpen(true) }
  const submit = async (values: EnumForm) => {
    setActionError(null)
    try { const wasEditing = Boolean(editing); await save.mutateAsync(values); close(); onChanged?.(); void message.success(wasEditing ? '枚举已更新' : '枚举已创建') } catch (error: unknown) { setActionError(error) }
  }
  const confirmRemove = (item: ConfigEnum) => modal.confirm({ title: '删除枚举', content: `确认删除枚举“${item.name}”吗？`, okText: '删除', okButtonProps: { danger: true }, onOk: async () => { try { await remove.mutateAsync(item.id); onChanged?.(); void message.success('枚举已删除') } catch (error: unknown) { setActionError(error); throw error } } })

  return (
    <section aria-label="枚举定义" className="resource-panel">
      <header className="resource-toolbar"><p>枚举值用于限制配置字段的可选范围。</p>{canWrite ? <Button type="primary" size="small" onClick={showCreate}>创建枚举</Button> : null}</header>
      {actionError ?? enums.error ? <Alert className="management-alert" type="error" showIcon message={getApiErrorMessage(actionError ?? enums.error, actionError ? '保存枚举失败' : '加载枚举失败')} /> : null}
      <Table<ConfigEnum> rowKey="id" loading={enums.isLoading} dataSource={enums.data ?? []} locale={{ emptyText: '当前配置还没有枚举' }} pagination={false} scroll={{ x: 850 }} columns={[
        { title: '枚举标识', dataIndex: 'key', width: 160 }, { title: '名称', dataIndex: 'name', width: 160 }, { title: '描述', dataIndex: 'description' }, { title: '枚举值数', width: 100, render: (_, item) => item.values.length }, { title: '更新时间', dataIndex: 'updatedAt', width: 190 },
        ...(canWrite ? [{ title: '操作', width: 150, fixed: 'right' as const, render: (_: unknown, item: ConfigEnum) => <div className="table-actions"><Button type="link" onClick={() => showEdit(item)}>编辑</Button><Button type="link" danger onClick={() => confirmRemove(item)}>删除</Button></div> }] : []),
      ]} />
      <Modal title={editing ? '编辑枚举' : '创建枚举'} open={open} width={900} confirmLoading={save.isPending} onCancel={close} onOk={() => form.submit()} afterClose={() => form.resetFields()} destroyOnHidden>
        <Form form={form} layout="vertical" onFinish={submit} preserve={false}>
          <div className="form-grid"><Form.Item label="枚举标识" name="key" rules={[{ required: true, message: '请输入枚举标识' }, { pattern: /^[A-Za-z][A-Za-z0-9]*$/, message: '枚举标识只能包含字母和数字，且以字母开头' }]}><Input disabled={Boolean(editing)} maxLength={64} /></Form.Item><Form.Item label="枚举名称" name="name" rules={[{ required: true, message: '请输入枚举名称' }]}><Input maxLength={64} /></Form.Item></div>
          <Form.Item label="枚举描述" name="description"><Input.TextArea rows={2} maxLength={255} showCount /></Form.Item>
          <Form.List name="values">{(fields, { add, remove: removeValue }) => <div className="editor-list"><div className="editor-list-header"><strong>枚举值</strong><Button icon={<PlusOutlined />} onClick={() => add(emptyValue())}>添加枚举值</Button></div>{fields.map((field, index) => <div className="editor-row enum-value-row" key={field.key}><Form.Item name={[field.name, 'label']} rules={[{ required: true, message: '请输入显示文本' }]}><Input aria-label={`第 ${index + 1} 个显示文本`} placeholder="显示文本" /></Form.Item><Form.Item name={[field.name, 'value']} rules={[{ required: true, message: '请输入枚举值' }]}><Input aria-label={`第 ${index + 1} 个枚举值`} placeholder="例如 ENABLED" /></Form.Item><Form.Item name={[field.name, 'description']}><Input aria-label={`第 ${index + 1} 个描述`} placeholder="描述" /></Form.Item><Tooltip title="删除枚举值"><Button aria-label="删除枚举值" danger type="text" icon={<DeleteOutlined />} onClick={() => removeValue(field.name)} /></Tooltip></div>)}</div>}</Form.List>
        </Form>
      </Modal>
    </section>
  )
}

// web/src/features/config-center/enums/EnumsPanel.vue
<template>
  <section aria-label="枚举定义">
    <header class="enums-panel__toolbar">
      <p>枚举值用于限制配置字段的可选范围。</p>
      <el-button
        v-if="canWrite"
        type="primary"
        size="small"
        @click="openCreate"
      >
        创建枚举
      </el-button>
    </header>

    <el-table
      v-loading="loading"
      :data="enums"
      stripe
      empty-text="当前配置还没有枚举"
    >
      <el-table-column
        prop="key"
        label="枚举标识"
        min-width="150"
      />
      <el-table-column
        prop="name"
        label="名称"
        min-width="150"
      />
      <el-table-column
        prop="description"
        label="描述"
        min-width="220"
      />
      <el-table-column
        label="枚举值数"
        width="100"
        align="center"
      >
        <template #default="{ row }">
          {{ row.values.length }}
        </template>
      </el-table-column>
      <el-table-column
        prop="updatedAt"
        label="更新时间"
        width="190"
      />
      <el-table-column
        v-if="canWrite"
        label="操作"
        width="150"
        align="right"
      >
        <template #default="{ row }">
          <el-button
            type="text"
            @click="openEdit(row)"
          >
            编辑
          </el-button>
          <el-button
            class="enums-panel__danger"
            type="text"
            @click="remove(row)"
          >
            删除
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      :visible.sync="dialog.visible"
      :title="dialog.editing ? '编辑枚举' : '创建枚举'"
      width="900px"
      :close-on-click-modal="false"
      append-to-body
    >
      <el-form
        v-if="dialog.visible"
        ref="enumForm"
        :model="dialog.form"
        :rules="rules"
        label-width="88px"
      >
        <el-form-item
          label="枚举标识"
          prop="key"
        >
          <el-input
            v-model.trim="dialog.form.key"
            :disabled="dialog.editing"
            maxlength="64"
          />
        </el-form-item>
        <el-form-item
          label="枚举名称"
          prop="name"
        >
          <el-input
            v-model.trim="dialog.form.name"
            maxlength="64"
          />
        </el-form-item>
        <el-form-item
          label="枚举描述"
          prop="description"
        >
          <el-input
            v-model="dialog.form.description"
            type="textarea"
            :rows="2"
            maxlength="255"
            show-word-limit
          />
        </el-form-item>
        <el-form-item label="枚举值">
          <div class="enums-panel__value-header">
            <el-button
              type="primary"
              size="small"
              @click="addValue"
            >
              添加枚举值
            </el-button>
          </div>
          <el-table
            :data="dialog.form.values"
            border
            size="small"
          >
            <el-table-column
              label="显示文本"
              min-width="180"
            >
              <template #default="{ row }">
                <el-input
                  v-model.trim="row.label"
                  size="small"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="枚举值"
              min-width="180"
            >
              <template #default="{ row }">
                <el-input
                  v-model.trim="row.value"
                  size="small"
                  placeholder="例如 ENABLED"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="描述"
              min-width="220"
            >
              <template #default="{ row }">
                <el-input
                  v-model="row.description"
                  size="small"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="操作"
              width="70"
              align="center"
            >
              <template #default="{ $index }">
                <el-button
                  class="enums-panel__danger"
                  type="text"
                  @click="removeValue($index)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog.visible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="dialog.saving"
          @click="save"
        >
          保存
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import { createEnum, deleteEnum, updateEnum } from '@/api/enums'

function errorMessage(error, fallback) {
  return error?.response?.data?.message || error?.message || fallback
}

function emptyEnum() {
  return {
    key: '',
    name: '',
    description: '',
    values: [{ label: '', value: '', description: '' }],
  }
}

function requireValues(values) {
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error('枚举至少需要一个值')
  }
  const keys = new Set()
  values.forEach((item, index) => {
    if (!item.label) {
      throw new Error(`第 ${index + 1} 个枚举值缺少显示文本`)
    }
    if (!/^[A-Z][A-Z0-9_]*$/.test(item.value)) {
      throw new Error(`第 ${index + 1} 个枚举值必须使用大写字母、数字或下划线`)
    }
    if (keys.has(item.value)) {
      throw new Error(`枚举值重复: ${item.value}`)
    }
    keys.add(item.value)
  })
}

export default {
  name: 'EnumsPanel',

  props: {
    projectId: { type: Number, required: true },
    configId: { type: Number, required: true },
  },

  data() {
    return {
      loading: false,
      enums: [],
      dialog: {
        visible: false,
        editing: false,
        saving: false,
        form: emptyEnum(),
      },
      rules: {
        key: [
          { required: true, message: '请输入枚举标识', trigger: 'blur' },
          {
            pattern: /^[A-Za-z][A-Za-z0-9]*$/,
            message: '枚举标识只能包含字母和数字，且以字母开头',
            trigger: 'blur',
          },
        ],
        name: [
          { required: true, message: '请输入枚举名称', trigger: 'blur' },
        ],
      },
    }
  },

  computed: {
    environmentId() {
      return this.$store.state.environment.currentId
    },
    canWrite() {
      return this.$store.getters['environment/hasPermission']('enum:write')
    },
  },

  watch: {
    configId() {
      this.reload()
    },
  },

  created() {
    this.reload()
  },

  methods: {
    async reload(force = false) {
      this.loading = true
      try {
        const reply = await this.$store.dispatch('configCenter/loadEnums', {
          environmentId: this.environmentId,
          projectId: this.projectId,
          configId: this.configId,
          force,
        })
        this.enums = reply.list.map((item) => {
          if (!Array.isArray(item?.values)) {
            throw new TypeError('枚举响应缺少 values')
          }
          return item
        })
        this.$emit('loaded', this.enums)
      } catch (error) {
        this.$message.error(errorMessage(error, '加载枚举失败'))
      } finally {
        this.loading = false
      }
    },
    openCreate() {
      this.dialog.editing = false
      this.dialog.form = emptyEnum()
      this.dialog.visible = true
    },
    openEdit(configEnum) {
      this.dialog.editing = true
      this.dialog.form = {
        id: configEnum.id,
        key: configEnum.key,
        name: configEnum.name,
        description: configEnum.description || '',
        values: configEnum.values.map((item) => ({ ...item })),
        version: configEnum.version,
      }
      this.dialog.visible = true
    },
    addValue() {
      this.dialog.form.values.push({
        label: '',
        value: '',
        description: '',
      })
    },
    removeValue(index) {
      this.dialog.form.values.splice(index, 1)
    },
    async save() {
      const valid = await new Promise((resolve) => {
        this.$refs.enumForm.validate(resolve)
      })
      if (!valid) {
        return
      }
      this.dialog.saving = true
      try {
        requireValues(this.dialog.form.values)
        const request = {
          key: this.dialog.form.key,
          name: this.dialog.form.name,
          description: this.dialog.form.description,
          values: this.dialog.form.values,
        }
        if (this.dialog.editing) {
          await updateEnum(this.environmentId, {
            ...request,
            id: this.dialog.form.id,
            version: this.dialog.form.version,
          })
        } else {
          await createEnum(this.environmentId, {
            ...request,
            config_id: this.configId,
          })
        }
        this.dialog.visible = false
        this.$message.success(this.dialog.editing ? '枚举已更新' : '枚举已创建')
        await this.reload(true)
        this.$emit('changed')
      } catch (error) {
        this.$message.error(errorMessage(error, '保存枚举失败'))
      } finally {
        this.dialog.saving = false
      }
    },
    async remove(configEnum) {
      try {
        await this.$confirm(`确认删除枚举“${configEnum.name}”吗？`, '删除枚举', {
          type: 'warning',
          confirmButtonText: '删除',
          cancelButtonText: '取消',
        })
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      try {
        await deleteEnum(this.environmentId, configEnum.id)
        this.$message.success('枚举已删除')
        await this.reload(true)
        this.$emit('changed')
      } catch (error) {
        this.$message.error(errorMessage(error, '删除枚举失败'))
      }
    },
  },
}
</script>

<style scoped>
.enums-panel__toolbar,
.enums-panel__value-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 16px;
}

.enums-panel__toolbar p {
  margin: 0;
  color: #6b7280;
}

.enums-panel__value-header {
  justify-content: flex-end;
}

.enums-panel__danger {
  color: #f56c6c;
}
</style>
