// web/src/features/config-center/models/ModelsPanel.tsx
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Checkbox, Form, Input, Modal, Space, Table, Tooltip } from 'antd'
import { useMemo, useState } from 'react'

import { createModel, deleteModel, updateModel } from '@/api/models'
import type { Identifier } from '@/api/types'
import { queryKeys } from '@/app/query-keys'
import { useEnvironment } from '@/auth/environment-state'
import DataTypeSelector from '@/components/DataTypeSelector/DataTypeSelector'
import { getApiErrorMessage } from '@/api/errors'
import { parseEditorType, toApiType } from '@/domain/type-codec'
import { requireModelFields, type EditorModelField } from '../editor-validation'
import { type ConfigEnum, type ConfigModel, useModelsQuery } from '../queries'

type ModelForm = { key: string; name: string; description: string; fields: EditorModelField[] }
type Props = { projectId: Identifier; configId: Identifier; enums?: ConfigEnum[]; onChanged?: () => void }

export default function ModelsPanel({ projectId, configId, enums = [], onChanged }: Props) {
  const { message, modal } = App.useApp()
  const environment = useEnvironment()
  const queryClient = useQueryClient()
  const models = useModelsQuery(environment.currentId, projectId, configId)
  const canWrite = environment.hasPermission('structure:write')
  const [form] = Form.useForm<ModelForm>()
  const [editing, setEditing] = useState<ConfigModel | null>(null)
  const [open, setOpen] = useState(false)
  const [actionError, setActionError] = useState<unknown>(null)
  const limitedModels = useMemo(() => (models.data ?? []).filter((item) => item.id !== editing?.id), [editing?.id, models.data])
  const refresh = () => environment.currentId === null ? Promise.resolve() : queryClient.invalidateQueries({ queryKey: queryKeys.models(environment.currentId, projectId, configId) })
  const save = useMutation({
    mutationFn: (values: ModelForm) => {
      if (environment.currentId === null) throw new Error('当前没有可用环境')
      if (!editing) return createModel(environment.currentId, { config_id: configId, key: values.key, name: values.name, description: values.description })
      requireModelFields(values.fields)
      return updateModel(environment.currentId, {
        id: editing.id,
        key: values.key,
        name: values.name,
        description: values.description,
        version: editing.version,
        fields: values.fields.map((field) => ({ key: field.key, name: field.name, description: field.description || '', is_array: Boolean(field.isArray), type: toApiType(parseEditorType(field.type)) })),
      })
    },
    onSuccess: refresh,
  })
  const remove = useMutation({
    mutationFn: (id: Identifier) => {
      if (environment.currentId === null) throw new Error('当前没有可用环境')
      return deleteModel(environment.currentId, id)
    },
    onSuccess: refresh,
  })

  const close = () => { setOpen(false); setEditing(null); form.resetFields() }
  const showCreate = () => { setActionError(null); setEditing(null); form.setFieldsValue({ key: '', name: '', description: '', fields: [] }); setOpen(true) }
  const showEdit = (model: ConfigModel) => {
    setActionError(null)
    setEditing(model)
    form.setFieldsValue({ key: model.key, name: model.name, description: model.description ?? '', fields: model.fields.map((field) => ({ key: field.key, name: field.name ?? field.key, description: field.description ?? '', isArray: Boolean(field.isArray), type: JSON.stringify(field.type) })) })
    setOpen(true)
  }
  const submit = async (values: ModelForm) => {
    setActionError(null)
    try {
      const wasEditing = Boolean(editing)
      await save.mutateAsync(values)
      close()
      onChanged?.()
      void message.success(wasEditing ? '模型已更新' : '模型已创建')
    } catch (error: unknown) { setActionError(error) }
  }
  const confirmRemove = (model: ConfigModel) => modal.confirm({
    title: '删除模型', content: `确认删除模型“${model.name}”吗？`, okText: '删除', okButtonProps: { danger: true },
    onOk: async () => { try { await remove.mutateAsync(model.id); onChanged?.(); void message.success('模型已删除') } catch (error: unknown) { setActionError(error); throw error } },
  })

  return (
    <section aria-label="模型定义" className="resource-panel">
      <header className="resource-toolbar"><p>模型可以被当前配置的字段引用。</p>{canWrite ? <Button type="primary" size="small" onClick={showCreate}>创建模型</Button> : null}</header>
      {actionError ?? models.error ? <Alert className="management-alert" type="error" showIcon message={getApiErrorMessage(actionError ?? models.error, actionError ? '保存模型失败' : '加载模型失败')} /> : null}
      <Table<ConfigModel> rowKey="id" loading={models.isLoading} dataSource={models.data ?? []} locale={{ emptyText: '当前配置还没有模型' }} pagination={false} scroll={{ x: 850 }} columns={[
        { title: '模型标识', dataIndex: 'key', width: 160 }, { title: '名称', dataIndex: 'name', width: 160 }, { title: '描述', dataIndex: 'description' },
        { title: '字段数', width: 90, render: (_, model) => model.fields.length }, { title: '更新时间', dataIndex: 'updatedAt', width: 190 },
        ...(canWrite ? [{ title: '操作', width: 150, fixed: 'right' as const, render: (_: unknown, model: ConfigModel) => <div className="table-actions"><Button type="link" onClick={() => showEdit(model)}>编辑</Button><Button type="link" danger onClick={() => confirmRemove(model)}>删除</Button></div> }] : []),
      ]} />
      <Modal title={editing ? '编辑模型' : '创建模型'} open={open} width={1100} confirmLoading={save.isPending} onCancel={close} onOk={() => form.submit()} afterClose={() => form.resetFields()} destroyOnHidden>
        <Form form={form} layout="vertical" onFinish={submit} preserve={false}>
          <div className="form-grid"><Form.Item label="模型标识" name="key" rules={[{ required: true, message: '请输入模型标识' }, { pattern: /^[A-Za-z][A-Za-z0-9]*$/, message: '模型标识只能包含字母和数字，且以字母开头' }]}><Input disabled={Boolean(editing)} maxLength={64} /></Form.Item><Form.Item label="模型名称" name="name" rules={[{ required: true, message: '请输入模型名称' }]}><Input maxLength={64} /></Form.Item></div>
          <Form.Item label="模型描述" name="description"><Input.TextArea rows={2} maxLength={255} showCount /></Form.Item>
          {editing ? <Form.List name="fields">{(fields, { add, remove: removeField, move }) => <div className="editor-list"><div className="editor-list-header"><strong>字段</strong><Button icon={<PlusOutlined />} onClick={() => add({ key: '', name: '', description: '', isArray: false, type: JSON.stringify({ baseType: 'String' }) })}>添加字段</Button></div>{fields.map((field, index) => <div className="editor-row model-field-row" key={field.key}><Space.Compact className="move-buttons"><Tooltip title="上移字段"><Button aria-label="上移字段" icon={<ArrowUpOutlined />} disabled={index === 0} onClick={() => move(index, index - 1)} /></Tooltip><Tooltip title="下移字段"><Button aria-label="下移字段" icon={<ArrowDownOutlined />} disabled={index === fields.length - 1} onClick={() => move(index, index + 1)} /></Tooltip></Space.Compact><Form.Item name={[field.name, 'key']} rules={[{ required: true, message: '请输入字段标识' }]}><Input placeholder="字段标识" /></Form.Item><Form.Item name={[field.name, 'name']} rules={[{ required: true, message: '请输入字段名称' }]}><Input placeholder="字段名称" /></Form.Item><Form.Item name={[field.name, 'type']} rules={[{ required: true, message: '请选择字段类型' }]}><DataTypeSelector models={models.data ?? []} limitedModels={limitedModels} enums={enums} limit /></Form.Item><Form.Item name={[field.name, 'description']}><Input placeholder="描述" /></Form.Item><Form.Item name={[field.name, 'isArray']} valuePropName="checked"><Checkbox>数组</Checkbox></Form.Item><Tooltip title="删除字段"><Button aria-label="删除字段" danger type="text" icon={<DeleteOutlined />} onClick={() => removeField(field.name)} /></Tooltip></div>)}</div>}</Form.List> : null}
        </Form>
      </Modal>
    </section>
  )
}

// web/src/features/config-center/models/ModelsPanel.vue
<template>
  <section aria-label="模型定义">
    <header class="models-panel__toolbar">
      <p>模型可以被当前配置的字段引用。</p>
      <el-button
        v-if="canWrite"
        type="primary"
        size="small"
        @click="openCreate"
      >
        创建模型
      </el-button>
    </header>

    <el-table
      v-loading="loading"
      :data="models"
      stripe
      empty-text="当前配置还没有模型"
    >
      <el-table-column
        prop="key"
        label="模型标识"
        min-width="150"
      />
      <el-table-column
        prop="name"
        label="名称"
        min-width="150"
      />
      <el-table-column
        prop="description"
        label="描述"
        min-width="220"
      />
      <el-table-column
        label="字段数"
        width="90"
        align="center"
      >
        <template #default="{ row }">
          {{ row.fields.length }}
        </template>
      </el-table-column>
      <el-table-column
        prop="updatedAt"
        label="更新时间"
        width="190"
      />
      <el-table-column
        v-if="canWrite"
        label="操作"
        width="150"
        align="right"
      >
        <template #default="{ row }">
          <el-button
            type="text"
            @click="openEdit(row)"
          >
            编辑
          </el-button>
          <el-button
            class="models-panel__danger"
            type="text"
            @click="remove(row)"
          >
            删除
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      :visible.sync="dialog.visible"
      :title="dialog.editing ? '编辑模型' : '创建模型'"
      width="1100px"
      :close-on-click-modal="false"
      append-to-body
    >
      <el-form
        v-if="dialog.visible"
        ref="modelForm"
        :model="dialog.form"
        :rules="rules"
        label-width="88px"
      >
        <el-form-item
          label="模型标识"
          prop="key"
        >
          <el-input
            v-model.trim="dialog.form.key"
            :disabled="dialog.editing"
            maxlength="64"
          />
        </el-form-item>
        <el-form-item
          label="模型名称"
          prop="name"
        >
          <el-input
            v-model.trim="dialog.form.name"
            maxlength="64"
          />
        </el-form-item>
        <el-form-item
          label="模型描述"
          prop="description"
        >
          <el-input
            v-model="dialog.form.description"
            type="textarea"
            :rows="2"
            maxlength="255"
            show-word-limit
          />
        </el-form-item>

        <el-form-item
          v-if="dialog.editing"
          label="字段"
        >
          <div class="models-panel__field-header">
            <el-button
              size="small"
              type="primary"
              @click="addField"
            >
              添加字段
            </el-button>
          </div>
          <el-table
            :data="dialog.form.fields"
            border
            size="small"
          >
            <el-table-column
              label="排序"
              width="90"
              align="center"
            >
              <template #default="{ $index }">
                <el-button
                  icon="el-icon-top"
                  type="text"
                  :disabled="$index === 0"
                  aria-label="上移字段"
                  @click="moveField($index, -1)"
                />
                <el-button
                  icon="el-icon-bottom"
                  type="text"
                  :disabled="$index === dialog.form.fields.length - 1"
                  aria-label="下移字段"
                  @click="moveField($index, 1)"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="字段标识"
              min-width="140"
            >
              <template #default="{ row }">
                <el-input
                  v-model.trim="row.key"
                  size="small"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="字段名称"
              min-width="130"
            >
              <template #default="{ row }">
                <el-input
                  v-model.trim="row.name"
                  size="small"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="字段类型"
              min-width="180"
            >
              <template #default="{ row }">
                <DataTypeSelector
                  v-model="row.type"
                  :models="models"
                  :limited-models="limitedModels"
                  :enums="enums"
                  limit
                />
              </template>
            </el-table-column>
            <el-table-column
              label="描述"
              min-width="160"
            >
              <template #default="{ row }">
                <el-input
                  v-model="row.description"
                  size="small"
                />
              </template>
            </el-table-column>
            <el-table-column
              label="数组"
              width="70"
              align="center"
            >
              <template #default="{ row }">
                <el-checkbox v-model="row.isArray" />
              </template>
            </el-table-column>
            <el-table-column
              label="操作"
              width="70"
              align="center"
            >
              <template #default="{ $index }">
                <el-button
                  class="models-panel__danger"
                  type="text"
                  @click="removeField($index)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog.visible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="dialog.saving"
          @click="save"
        >
          保存
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import { createModel, deleteModel, updateModel } from '@/api/models'
import DataTypeSelector from '@/components/DataTypeSelector'
import {
  normalizeModel,
  parseEditorType,
  toApiType,
} from '@/features/config-center/configs/type-codec'

function errorMessage(error, fallback) {
  return error?.response?.data?.message || error?.message || fallback
}

function emptyModel() {
  return { key: '', name: '', description: '', fields: [] }
}

function requireFields(fields) {
  if (!Array.isArray(fields) || fields.length === 0) {
    throw new Error('模型至少需要一个字段')
  }
  const keys = new Set()
  fields.forEach((field, index) => {
    if (!/^[A-Za-z][A-Za-z0-9]*$/.test(field.key)) {
      throw new Error(`第 ${index + 1} 个字段的标识不合法`)
    }
    if (!field.name) {
      throw new Error(`第 ${index + 1} 个字段缺少名称`)
    }
    if (keys.has(field.key)) {
      throw new Error(`字段标识重复: ${field.key}`)
    }
    keys.add(field.key)
    parseEditorType(field.type)
  })
}

export default {
  name: 'ModelsPanel',

  components: { DataTypeSelector },

  props: {
    projectId: { type: Number, required: true },
    configId: { type: Number, required: true },
    enums: { type: Array, default: () => [] },
  },

  data() {
    return {
      loading: false,
      models: [],
      dialog: {
        visible: false,
        editing: false,
        saving: false,
        form: emptyModel(),
      },
      rules: {
        key: [
          { required: true, message: '请输入模型标识', trigger: 'blur' },
          {
            pattern: /^[A-Za-z][A-Za-z0-9]*$/,
            message: '模型标识只能包含字母和数字，且以字母开头',
            trigger: 'blur',
          },
        ],
        name: [
          { required: true, message: '请输入模型名称', trigger: 'blur' },
        ],
      },
    }
  },

  computed: {
    environmentId() {
      return this.$store.state.environment.currentId
    },
    canWrite() {
      return this.$store.getters['environment/hasPermission'](
        'structure:write',
      )
    },
    limitedModels() {
      if (!this.dialog.editing) {
        return this.models
      }
      return this.models.filter((item) => item.id !== this.dialog.form.id)
    },
  },

  watch: {
    configId() {
      this.reload()
    },
  },

  created() {
    this.reload()
  },

  methods: {
    async reload(force = false) {
      this.loading = true
      try {
        const reply = await this.$store.dispatch('configCenter/loadModels', {
          environmentId: this.environmentId,
          projectId: this.projectId,
          configId: this.configId,
          force,
        })
        this.models = reply.list.map(normalizeModel)
        this.$emit('loaded', this.models)
      } catch (error) {
        this.$message.error(errorMessage(error, '加载模型失败'))
      } finally {
        this.loading = false
      }
    },
    openCreate() {
      this.dialog.editing = false
      this.dialog.form = emptyModel()
      this.dialog.visible = true
    },
    openEdit(model) {
      this.dialog.editing = true
      this.dialog.form = {
        id: model.id,
        key: model.key,
        name: model.name,
        description: model.description || '',
        version: model.version,
        fields: model.fields.map((field) => ({
          ...field,
          type: JSON.stringify(field.type),
        })),
      }
      this.dialog.visible = true
    },
    addField() {
      this.dialog.form.fields.push({
        key: '',
        name: '',
        description: '',
        isArray: false,
        type: JSON.stringify({ baseType: 'String' }),
      })
    },
    removeField(index) {
      this.dialog.form.fields.splice(index, 1)
    },
    moveField(index, offset) {
      const target = index + offset
      if (target < 0 || target >= this.dialog.form.fields.length) {
        return
      }
      const fields = [...this.dialog.form.fields]
      const current = fields[index]
      fields[index] = fields[target]
      fields[target] = current
      this.dialog.form.fields = fields
    },
    async save() {
      const valid = await new Promise((resolve) => {
        this.$refs.modelForm.validate(resolve)
      })
      if (!valid) {
        return
      }
      this.dialog.saving = true
      try {
        if (this.dialog.editing) {
          requireFields(this.dialog.form.fields)
          await updateModel(this.environmentId, {
            id: this.dialog.form.id,
            key: this.dialog.form.key,
            name: this.dialog.form.name,
            description: this.dialog.form.description,
            version: this.dialog.form.version,
            fields: this.dialog.form.fields.map((field) => ({
              key: field.key,
              name: field.name,
              description: field.description || '',
              is_array: Boolean(field.isArray),
              type: toApiType(parseEditorType(field.type)),
            })),
          })
        } else {
          await createModel(this.environmentId, {
            config_id: this.configId,
            key: this.dialog.form.key,
            name: this.dialog.form.name,
            description: this.dialog.form.description,
          })
        }
        this.dialog.visible = false
        this.$message.success(this.dialog.editing ? '模型已更新' : '模型已创建')
        await this.reload(true)
        this.$emit('changed')
      } catch (error) {
        this.$message.error(errorMessage(error, '保存模型失败'))
      } finally {
        this.dialog.saving = false
      }
    },
    async remove(model) {
      try {
        await this.$confirm(`确认删除模型“${model.name}”吗？`, '删除模型', {
          type: 'warning',
          confirmButtonText: '删除',
          cancelButtonText: '取消',
        })
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      try {
        await deleteModel(this.environmentId, model.id)
        this.$message.success('模型已删除')
        await this.reload(true)
        this.$emit('changed')
      } catch (error) {
        this.$message.error(errorMessage(error, '删除模型失败'))
      }
    },
  },
}
</script>

<style scoped>
.models-panel__toolbar,
.models-panel__field-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 16px;
}

.models-panel__toolbar p {
  margin: 0;
  color: #6b7280;
}

.models-panel__field-header {
  justify-content: flex-end;
}

.models-panel__danger {
  color: #f56c6c;
}
</style>
