// web/src/features/config-center/configs/ConfigDetailPage.vue
<template>
  <section
    v-loading="loading"
    class="config-detail"
    aria-labelledby="config-detail-title"
  >
    <el-page-header @back="goBack">
      <template #content>
        <div class="config-detail__title">
          <span id="config-detail-title">
            {{ config ? config.key : '配置详情' }}
          </span>
          <EnvironmentTag :environment="environment" />
        </div>
      </template>
    </el-page-header>

    <el-card
      v-if="config"
      shadow="never"
    >
      <header class="config-detail__summary-header">
        <div>
          <h1>{{ config.description || config.key }}</h1>
          <p>{{ project ? project.name : '' }} · {{ config.key }}</p>
        </div>
        <el-button
          v-if="canWriteConfig"
          type="primary"
          size="small"
          @click="openConfigEditor"
        >
          修改配置定义
        </el-button>
      </header>
      <el-descriptions
        :column="3"
        border
        size="small"
      >
        <el-descriptions-item label="数据类型">
          {{ typeLabel }}
        </el-descriptions-item>
        <el-descriptions-item label="数组">
          {{ config.isArray ? '是' : '否' }}
        </el-descriptions-item>
        <el-descriptions-item label="版本">
          {{ config.version }}
        </el-descriptions-item>
      </el-descriptions>
    </el-card>

    <el-card
      v-if="config"
      class="config-detail__tabs"
      shadow="never"
    >
      <el-tabs v-model="activeTab">
        <el-tab-pane
          label="配置内容"
          name="content"
        >
          <div class="config-detail__editor-grid">
            <div class="config-detail__form-pane">
              <SchemaForm
                v-if="tree"
                :key="schemaFormScopeKey"
                ref="schemaForm"
                :config="tree"
                :value="config.value || ''"
                :disabled="!canWriteConfig"
                :models="models"
                :enums="enums"
                :file-upload-component="scopedFileUploadComponent"
              />
              <el-alert
                v-else
                type="warning"
                :closable="false"
                title="配置结构不可用，请先修改配置定义。"
              />
            </div>
            <div class="config-detail__json-pane">
              <MonacoEditor
                :value="previewValue"
                disabled
              />
            </div>
          </div>
          <div
            v-if="canWriteConfig && tree"
            class="config-detail__content-actions"
          >
            <el-button @click="preview">
              刷新 JSON 预览
            </el-button>
            <el-button
              type="primary"
              :loading="savingValue"
              @click="saveValue"
            >
              保存配置内容
            </el-button>
          </div>
        </el-tab-pane>
        <el-tab-pane
          label="模型定义"
          name="models"
        >
          <ModelsPanel
            v-if="activeTab === 'models'"
            :project-id="projectId"
            :config-id="configId"
            :enums="enums"
            @loaded="models = $event"
            @changed="reload"
          />
        </el-tab-pane>
        <el-tab-pane
          label="枚举定义"
          name="enums"
        >
          <EnumsPanel
            v-if="activeTab === 'enums'"
            :project-id="projectId"
            :config-id="configId"
            @loaded="enums = $event"
            @changed="reload"
          />
        </el-tab-pane>
        <el-tab-pane
          v-if="canReadSnapshots"
          label="快照"
          name="snapshots"
        >
          <SnapshotsPanel
            v-if="activeTab === 'snapshots'"
            :project-id="projectId"
            :config-id="configId"
            @changed="reload"
          />
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <el-dialog
      :visible.sync="dialog.visible"
      title="修改配置定义"
      width="560px"
      :close-on-click-modal="false"
      append-to-body
    >
      <el-form
        v-if="dialog.visible"
        ref="definitionForm"
        :model="dialog.form"
        :rules="rules"
        label-width="88px"
      >
        <el-form-item label="配置标识">
          <el-input
            :value="config.key"
            disabled
          />
        </el-form-item>
        <el-form-item
          label="配置描述"
          prop="description"
        >
          <el-input
            v-model="dialog.form.description"
            maxlength="255"
            show-word-limit
          />
        </el-form-item>
        <el-form-item
          label="数据类型"
          prop="type"
        >
          <DataTypeSelector
            v-model="dialog.form.type"
            :models="models"
            :enums="enums"
          />
        </el-form-item>
        <el-form-item label="数组">
          <el-switch v-model="dialog.form.isArray" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog.visible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="dialog.saving"
          @click="saveDefinition"
        >
          保存
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import { getConfig, updateConfig, updateConfigValue } from '@/api/configs'
import { getProject } from '@/api/projects'
import DataTypeSelector from '@/components/DataTypeSelector'
import EnvironmentTag from '@/components/EnvironmentTag'
import { createScopedFileUpload } from '@/components/FileUpload/scoped'
import MonacoEditor from '@/components/MonacoEditor'
import SchemaForm from '@/components/SchemaForm'
import EnumsPanel from '@/features/config-center/enums/EnumsPanel.vue'
import ModelsPanel from '@/features/config-center/models/ModelsPanel.vue'
import SnapshotsPanel from '@/features/config-center/snapshots/SnapshotsPanel.vue'
import {
  normalizeModel,
  normalizeTree,
  parseEditorType,
  stringifyEditorType,
  toApiType,
  toEditorType,
} from './type-codec'

function errorMessage(error, fallback) {
  return error?.response?.data?.message || error?.message || fallback
}

function formatJSON(value) {
  if (value === '') {
    return ''
  }
  if (typeof value !== 'string') {
    throw new TypeError('配置值必须是 JSON 字符串')
  }
  return JSON.stringify(JSON.parse(value), null, 2)
}

function requireEnumList(reply) {
  if (!Array.isArray(reply?.list)) {
    throw new TypeError('枚举列表响应缺少 list')
  }
  reply.list.forEach((item) => {
    if (!Array.isArray(item?.values)) {
      throw new TypeError('枚举响应缺少 values')
    }
  })
  return reply.list
}

export default {
  name: 'ConfigDetailPage',

  components: {
    DataTypeSelector,
    EnumsPanel,
    EnvironmentTag,
    ModelsPanel,
    MonacoEditor,
    SchemaForm,
    SnapshotsPanel,
  },

  props: {
    projectId: { type: Number, required: true },
    configId: { type: Number, required: true },
  },

  data() {
    return {
      activeTab: 'content',
      loading: false,
      loadSequence: 0,
      savingValue: false,
      project: null,
      config: null,
      tree: null,
      models: [],
      enums: [],
      previewValue: '',
      dialog: {
        visible: false,
        saving: false,
        form: { description: '', type: '', isArray: false },
      },
      rules: {
        type: [
          { required: true, message: '请选择数据类型', trigger: 'change' },
        ],
      },
    }
  },

  computed: {
    environmentId() {
      return this.$store.state.environment.currentId
    },
    environment() {
      return this.$store.getters['environment/current']
    },
    canWriteConfig() {
      return this.$store.getters['environment/hasPermission']('config:write')
    },
    canReadSnapshots() {
      return this.$store.getters['environment/hasPermission']('snapshot:read')
    },
    schemaFormScopeKey() {
      return `${this.environmentId}:${this.projectId}:${this.configId}`
    },
    scopedFileUploadComponent() {
      return createScopedFileUpload(this.environmentId, this.projectId)
    },
    typeLabel() {
      if (!this.config?.type) {
        return '未设置'
      }
      const type = toEditorType(this.config.type)
      return type.baseType || type.structureKey || type.enumKey
    },
  },

  watch: {
    environmentId(environmentId, previousId) {
      if (!environmentId) {
        return
      }
      if (
        previousId !== null &&
        previousId !== undefined &&
        String(environmentId) !== String(previousId)
      ) {
        this.clearScopedResources()
        return
      }
      this.reload()
    },
    projectId() {
      this.clearScopedResources()
      this.reload()
    },
    configId() {
      this.clearScopedResources()
      this.reload()
    },
  },

  created() {
    if (this.environmentId) {
      this.reload()
    }
  },

  methods: {
    clearScopedResources() {
      this.project = null
      this.config = null
      this.tree = null
      this.models = []
      this.enums = []
      this.previewValue = ''
    },
    async reload() {
      if (!this.environmentId) {
        throw new Error('当前没有可用环境')
      }
      if (!Number.isInteger(this.projectId) || this.projectId <= 0) {
        throw new TypeError('projectId 必须是正整数')
      }
      if (!Number.isInteger(this.configId) || this.configId <= 0) {
        throw new TypeError('configId 必须是正整数')
      }
      const sequence = ++this.loadSequence
      this.loading = true
      try {
        const [projectReply, configReply, modelReply, enumReply] =
          await Promise.all([
            getProject(this.environmentId, this.projectId),
            getConfig(this.environmentId, this.configId),
            this.$store.dispatch('configCenter/loadModels', {
              environmentId: this.environmentId,
              projectId: this.projectId,
              configId: this.configId,
              force: true,
            }),
            this.$store.dispatch('configCenter/loadEnums', {
              environmentId: this.environmentId,
              projectId: this.projectId,
              configId: this.configId,
              force: true,
            }),
          ])
        if (!projectReply?.project) {
          throw new TypeError('项目详情响应缺少 project')
        }
        if (!configReply?.config) {
          throw new TypeError('配置详情响应缺少 config')
        }
        const models = modelReply.list.map(normalizeModel)
        const enums = requireEnumList(enumReply)
        const tree = configReply.tree
          ? normalizeTree(configReply.tree)
          : null
        const previewValue = formatJSON(configReply.config.value || '')

        if (sequence === this.loadSequence) {
          this.project = projectReply.project
          this.config = configReply.config
          this.models = models
          this.enums = enums
          this.tree = tree
          this.previewValue = previewValue
        }
      } catch (error) {
        this.$message.error(errorMessage(error, '加载配置详情失败'))
      } finally {
        if (sequence === this.loadSequence) {
          this.loading = false
        }
      }
    },
    goBack() {
      this.$router.push({
        name: 'project-configs',
        params: { projectId: String(this.projectId) },
      })
    },
    preview() {
      if (!this.$refs.schemaForm) {
        throw new Error('配置表单尚未加载')
      }
      this.previewValue = JSON.stringify(
        this.$refs.schemaForm.getValue(),
        null,
        2,
      )
    },
    async saveValue() {
      this.preview()
      this.savingValue = true
      try {
        await updateConfigValue(this.environmentId, {
          id: this.config.id,
          version: this.config.version,
          value: JSON.stringify(this.$refs.schemaForm.getValue()),
        })
        this.$message.success('配置内容已保存')
        await this.reload()
      } catch (error) {
        this.$message.error(errorMessage(error, '保存配置内容失败'))
      } finally {
        this.savingValue = false
      }
    },
    openConfigEditor() {
      this.dialog.form = {
        description: this.config.description || '',
        type: stringifyEditorType(this.config.type),
        isArray: Boolean(this.config.isArray),
      }
      this.dialog.visible = true
    },
    async saveDefinition() {
      const valid = await new Promise((resolve) => {
        this.$refs.definitionForm.validate(resolve)
      })
      if (!valid) {
        return
      }
      this.dialog.saving = true
      try {
        await updateConfig(this.environmentId, {
          id: this.config.id,
          description: this.dialog.form.description,
          type: toApiType(parseEditorType(this.dialog.form.type)),
          is_array: Boolean(this.dialog.form.isArray),
          version: this.config.version,
        })
        this.dialog.visible = false
        this.$message.success('配置定义已更新')
        await this.reload()
      } catch (error) {
        this.$message.error(errorMessage(error, '保存配置定义失败'))
      } finally {
        this.dialog.saving = false
      }
    },
  },
}
</script>

<style scoped>
.config-detail {
  display: grid;
  gap: 20px;
  min-height: 320px;
}

.config-detail__title,
.config-detail__summary-header,
.config-detail__content-actions {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.config-detail__title {
  justify-content: flex-start;
  font-weight: 600;
}

.config-detail__summary-header {
  margin-bottom: 20px;
}

.config-detail__summary-header h1,
.config-detail__summary-header p {
  margin: 0;
}

.config-detail__summary-header p {
  margin-top: 6px;
  color: #6b7280;
}

.config-detail__tabs {
  min-height: 480px;
}

.config-detail__editor-grid {
  display: grid;
  grid-template-columns: minmax(0, 3fr) minmax(320px, 2fr);
  gap: 20px;
  min-height: 360px;
  padding: 12px 0;
}

.config-detail__form-pane,
.config-detail__json-pane {
  min-width: 0;
  padding: 16px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.config-detail__content-actions {
  justify-content: center;
  padding-top: 16px;
}

@media (max-width: 960px) {
  .config-detail__editor-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// web/src/features/config-center/configs/ConfigDetailPage.tsx
import { ArrowLeftOutlined } from '@ant-design/icons'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Descriptions, Form, Input, Modal, Switch, Tabs, Tooltip } from 'antd'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'

import { updateConfig, updateConfigValue } from '@/api/configs'
import { getApiErrorMessage } from '@/api/errors'
import { queryKeys } from '@/app/query-keys'
import { useEnvironment } from '@/auth/environment-state'
import DataTypeSelector from '@/components/DataTypeSelector/DataTypeSelector'
import EnvironmentTag from '@/components/EnvironmentTag/EnvironmentTag'
import { createScopedFileUpload } from '@/components/FileUpload/scoped'
import MonacoEditor from '@/components/MonacoEditor/MonacoEditor'
import SchemaForm, { type SchemaFormHandle } from '@/components/SchemaForm/SchemaForm'
import { parseEditorType, stringifyEditorType, toApiType, toEditorType } from '@/domain/type-codec'
import EnumsPanel from '@/features/config-center/enums/EnumsPanel'
import ModelsPanel from '@/features/config-center/models/ModelsPanel'
import SnapshotsPanel from '@/features/config-center/snapshots/SnapshotsPanel'
import { useConfigDetailQuery, useEnumsQuery, useModelsQuery, useProjectQuery } from '../queries'
import { formatConfigJSON } from './detail-model'

type DefinitionForm = { description: string; type: string; isArray: boolean }

function routeId(value: string | undefined, name: string): number {
  if (!value || !/^[1-9]\d*$/.test(value)) throw new TypeError(`${name} 必须是正整数`)
  return Number(value)
}

export default function ConfigDetailPage() {
  const params = useParams()
  const projectId = routeId(params.projectId, 'projectId')
  const configId = routeId(params.configId, 'configId')
  const navigate = useNavigate()
  const { message } = App.useApp()
  const environment = useEnvironment()
  const queryClient = useQueryClient()
  const project = useProjectQuery(environment.currentId, projectId)
  const detail = useConfigDetailQuery(environment.currentId, projectId, configId)
  const models = useModelsQuery(environment.currentId, projectId, configId)
  const enums = useEnumsQuery(environment.currentId, projectId, configId)
  const config = detail.data?.config
  const tree = detail.data?.tree
  const [activeTab, setActiveTab] = useState('content')
  const [previewValue, setPreviewValue] = useState('')
  const [definitionOpen, setDefinitionOpen] = useState(false)
  const [actionError, setActionError] = useState<unknown>(null)
  const [definitionForm] = Form.useForm<DefinitionForm>()
  const schemaForm = useRef<SchemaFormHandle>(null)
  const canWriteConfig = environment.hasPermission('config:write')
  const canReadSnapshots = environment.hasPermission('snapshot:read')
  const ScopedFileUpload = useMemo(() => environment.currentId === null ? undefined : createScopedFileUpload(environment.currentId, projectId), [environment.currentId, projectId])
  const refresh = () => environment.currentId === null ? Promise.resolve() : queryClient.invalidateQueries({ queryKey: queryKeys.config(environment.currentId, projectId, configId) })
  const saveValue = useMutation({
    mutationFn: (value: unknown) => {
      if (environment.currentId === null || !config) throw new Error('配置尚未加载')
      return updateConfigValue(environment.currentId, { id: config.id, version: config.version, value: JSON.stringify(value) })
    },
    onSuccess: refresh,
  })
  const saveDefinition = useMutation({
    mutationFn: (values: DefinitionForm) => {
      if (environment.currentId === null || !config) throw new Error('配置尚未加载')
      return updateConfig(environment.currentId, { id: config.id, description: values.description, type: toApiType(parseEditorType(values.type)), is_array: Boolean(values.isArray), version: config.version })
    },
    onSuccess: refresh,
  })

  useEffect(() => {
    if (!config) { setPreviewValue(''); return }
    try { setPreviewValue(formatConfigJSON(config.value)) } catch (error: unknown) { setActionError(error) }
  }, [config])

  const preview = () => {
    if (!schemaForm.current) throw new Error('配置表单尚未加载')
    const value = schemaForm.current.getValue()
    setPreviewValue(JSON.stringify(value, null, 2))
    return value
  }
  const submitValue = async () => {
    setActionError(null)
    try { await saveValue.mutateAsync(preview()); void message.success('配置内容已保存') } catch (error: unknown) { setActionError(error) }
  }
  const openDefinition = () => {
    if (!config) throw new Error('配置尚未加载')
    definitionForm.setFieldsValue({ description: config.description ?? '', type: stringifyEditorType(config.type), isArray: config.isArray })
    setDefinitionOpen(true)
  }
  const submitDefinition = async (values: DefinitionForm) => {
    setActionError(null)
    try { await saveDefinition.mutateAsync(values); setDefinitionOpen(false); definitionForm.resetFields(); void message.success('配置定义已更新') } catch (error: unknown) { setActionError(error) }
  }
  const editorType = config ? toEditorType(config.type) : null
  const typeLabel = editorType?.baseType ?? editorType?.structureKey ?? editorType?.enumKey ?? '未设置'
  const queryError = project.error ?? detail.error ?? models.error ?? enums.error

  return (
    <section className="config-detail" aria-labelledby="config-detail-title">
      <header className="detail-header"><Tooltip title="返回配置列表"><Button aria-label="返回配置列表" type="text" icon={<ArrowLeftOutlined />} onClick={() => navigate(`/projects/${projectId}/configs`)} /></Tooltip><div className="title-row"><h1 id="config-detail-title">{config?.key ?? '配置详情'}</h1><EnvironmentTag environment={environment.current} /></div></header>
      {actionError ?? queryError ? <Alert type="error" showIcon message={getApiErrorMessage(actionError ?? queryError, actionError ? '配置操作失败' : '加载配置详情失败')} /> : null}
      {config ? <section className="config-summary"><header className="catalog-header"><div><h2>{config.description || config.key}</h2><p>{project.data?.name ?? ''} · {config.key}</p></div>{canWriteConfig ? <Button type="primary" onClick={openDefinition}>修改配置定义</Button> : null}</header><Descriptions bordered size="small" column={{ xs: 1, sm: 3 }} items={[{ key: 'type', label: '数据类型', children: typeLabel }, { key: 'array', label: '数组', children: config.isArray ? '是' : '否' }, { key: 'version', label: '版本', children: config.version }]} /></section> : null}
      {config ? <section className="config-workspace"><Tabs activeKey={activeTab} onChange={setActiveTab} items={[
        { key: 'content', label: '配置内容', children: <><div className="config-editor-grid"><div className="form-pane">{tree && ScopedFileUpload ? <SchemaForm key={`${environment.currentId}:${projectId}:${configId}`} ref={schemaForm} config={tree} value={config.value} disabled={!canWriteConfig} models={models.data ?? []} enums={enums.data ?? []} fileUploadComponent={ScopedFileUpload} /> : <Alert type="warning" message="配置结构不可用，请先修改配置定义。" />}</div><div className="json-pane"><MonacoEditor value={previewValue} disabled /></div></div>{canWriteConfig && tree ? <div className="content-actions"><Button onClick={() => { try { preview() } catch (error: unknown) { setActionError(error) } }}>刷新 JSON 预览</Button><Button type="primary" loading={saveValue.isPending} onClick={() => void submitValue()}>保存配置内容</Button></div> : null}</> },
        { key: 'models', label: '模型定义', children: activeTab === 'models' ? <ModelsPanel projectId={projectId} configId={configId} enums={enums.data ?? []} onChanged={() => void refresh()} /> : null },
        { key: 'enums', label: '枚举定义', children: activeTab === 'enums' ? <EnumsPanel projectId={projectId} configId={configId} onChanged={() => void refresh()} /> : null },
        ...(canReadSnapshots ? [{ key: 'snapshots', label: '快照', children: activeTab === 'snapshots' ? <SnapshotsPanel projectId={projectId} configId={configId} onChanged={() => void refresh()} /> : null }] : []),
      ]} /></section> : null}
      <Modal title="修改配置定义" open={definitionOpen} width={560} confirmLoading={saveDefinition.isPending} onCancel={() => { setDefinitionOpen(false); definitionForm.resetFields() }} onOk={() => definitionForm.submit()} afterClose={() => definitionForm.resetFields()} destroyOnHidden>
        <Form form={definitionForm} layout="vertical" onFinish={submitDefinition} preserve={false}>
          <Form.Item label="配置标识"><Input value={config?.key} disabled /></Form.Item><Form.Item label="配置描述" name="description"><Input maxLength={255} showCount /></Form.Item><Form.Item label="数据类型" name="type" rules={[{ required: true, message: '请选择数据类型' }]}><DataTypeSelector models={models.data ?? []} enums={enums.data ?? []} /></Form.Item><Form.Item label="数组" name="isArray" valuePropName="checked"><Switch /></Form.Item>
        </Form>
      </Modal>
    </section>
  )
}
