// web/src/features/config-center/snapshots/SnapshotsPanel.vue
<template>
  <section aria-label="快照管理">
    <el-alert
      v-if="errorMessage"
      :title="errorMessage"
      type="error"
      :closable="false"
      show-icon
    />

    <header class="snapshots-panel__toolbar">
      <p>快照用于比较、还原、发布和跨环境复用配置。</p>
      <div>
        <el-button
          size="small"
          :loading="loading"
          @click="reload"
        >
          刷新
        </el-button>
        <el-button
          v-if="canWrite"
          type="primary"
          size="small"
          @click="openCreate"
        >
          创建快照
        </el-button>
      </div>
    </header>

    <el-table
      v-loading="loading"
      :data="snapshots"
      stripe
      empty-text="当前配置还没有快照"
    >
      <el-table-column
        prop="id"
        label="ID"
        width="80"
      />
      <el-table-column
        prop="description"
        label="描述"
        min-width="220"
      />
      <el-table-column
        label="标签"
        min-width="180"
      >
        <template #default="{ row }">
          <el-tag
            v-for="tag in row.tags"
            :key="tag"
            class="snapshots-panel__tag"
            size="mini"
            type="info"
          >
            {{ tag }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column
        label="状态"
        width="110"
      >
        <template #default="{ row }">
          <el-tag
            :type="row.status === 'RELEASED' ? 'success' : 'info'"
            size="small"
          >
            {{ statusLabel(row.status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column
        prop="createdBy"
        label="创建人"
        width="130"
      />
      <el-table-column
        prop="createdAt"
        label="创建时间"
        width="190"
      />
      <el-table-column
        label="操作"
        min-width="430"
        align="right"
      >
        <template #default="{ row }">
          <el-button
            type="text"
            @click="openCompare(row)"
          >
            比较
          </el-button>
          <el-button
            v-if="canWrite"
            type="text"
            @click="restore(row)"
          >
            还原
          </el-button>
          <el-button
            v-if="canPublish && row.status === 'UNRELEASED'"
            type="text"
            @click="publish(row)"
          >
            发布
          </el-button>
          <el-button
            v-if="canPublish && row.status === 'RELEASED'"
            type="text"
            @click="unpublish(row)"
          >
            下线
          </el-button>
          <el-button
            v-if="canExport"
            type="text"
            @click="download(row)"
          >
            导出
          </el-button>
          <el-button
            v-if="canExport"
            type="text"
            @click="openImport(row)"
          >
            导入到环境
          </el-button>
          <el-button
            v-if="canWrite && row.status === 'UNRELEASED'"
            class="snapshots-panel__danger"
            type="text"
            @click="remove(row)"
          >
            删除
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-pagination
      class="snapshots-panel__pagination"
      :current-page="page.page"
      :page-size="page.limit"
      :page-sizes="[10, 20, 50, 100]"
      :total="page.total"
      layout="total, sizes, prev, pager, next"
      @current-change="changePage"
      @size-change="changePageSize"
    />

    <el-dialog
      :visible.sync="createDialog.visible"
      title="创建快照"
      width="1100px"
      append-to-body
      :close-on-click-modal="false"
      @closed="clearCreate"
    >
      <el-form
        v-if="createDialog.visible"
        ref="createForm"
        :model="createDialog.form"
        :rules="createRules"
        label-width="88px"
      >
        <el-form-item
          label="快照标签"
          prop="tags"
        >
          <el-select
            v-model="createDialog.form.tags"
            multiple
            size="small"
          >
            <el-option
              v-for="tag in tagOptions"
              :key="tag.value"
              :label="tag.label"
              :value="tag.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item
          label="快照描述"
          prop="description"
        >
          <el-input
            v-model="createDialog.form.description"
            type="textarea"
            :rows="3"
            maxlength="255"
            show-word-limit
          />
        </el-form-item>
        <el-form-item label="配置变化">
          <p class="snapshots-panel__hint">
            左侧是当前配置，右侧是待创建快照。
          </p>
          <DiffEditor
            v-if="createDialog.previewReady"
            class="snapshots-panel__diff"
            :left-value="createDialog.currentContent"
            :right-value="createDialog.previewContent"
          />
          <div v-else>
            正在读取快照预览…
          </div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="createDialog.visible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="createDialog.saving"
          :disabled="!createDialog.previewReady"
          @click="createSnapshotRecord"
        >
          创建
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      :visible.sync="compareDialog.visible"
      title="快照内容比较"
      width="1100px"
      append-to-body
      @closed="clearCompare"
    >
      <p class="snapshots-panel__hint">
        左侧是当前配置，右侧是所选快照。
      </p>
      <DiffEditor
        v-if="compareDialog.ready"
        class="snapshots-panel__diff"
        :left-value="compareDialog.currentContent"
        :right-value="compareDialog.snapshotContent"
      />
      <div v-else>
        正在读取比较内容…
      </div>
    </el-dialog>

    <el-dialog
      :visible.sync="importDialog.visible"
      title="导入快照到目标环境"
      width="680px"
      append-to-body
      :close-on-click-modal="false"
      @closed="clearImport"
    >
      <el-alert
        v-if="importDialog.errorMessage"
        :title="importDialog.errorMessage"
        type="error"
        :closable="false"
        show-icon
      />
      <el-form
        v-if="importDialog.visible"
        ref="importForm"
        :model="importDialog.form"
        :rules="importRules"
        label-width="112px"
      >
        <el-form-item label="源快照">
          <el-input
            :value="`环境 ${environmentId} / 快照 ${importDialog.sourceSnapshotId}`"
            disabled
          />
        </el-form-item>
        <el-form-item
          label="目标环境"
          prop="targetEnvironmentId"
        >
          <el-select
            v-model="importDialog.form.targetEnvironmentId"
            filterable
            @change="loadTargetEnvironment"
          >
            <el-option
              v-for="environment in availableEnvironments"
              :key="String(environment.id)"
              :label="environment.name"
              :value="environment.id"
              :disabled="!environment.enabled"
            />
          </el-select>
        </el-form-item>
        <el-form-item
          label="目标项目"
          prop="targetProjectId"
        >
          <el-select
            v-model="importDialog.form.targetProjectId"
            filterable
            :disabled="!importDialog.targetHasPermission"
            @change="loadTargetConfigs"
          >
            <el-option
              v-for="project in importDialog.projects"
              :key="String(project.id)"
              :label="project.name"
              :value="project.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item
          label="冲突策略"
          prop="conflictStrategy"
        >
          <el-select v-model="importDialog.form.conflictStrategy">
            <el-option
              label="冲突时报错并创建新配置"
              value="FAIL"
            />
            <el-option
              label="替换指定配置"
              value="REPLACE"
            />
          </el-select>
        </el-form-item>
        <el-form-item
          v-if="importDialog.form.conflictStrategy === 'REPLACE'"
          label="目标配置"
          prop="targetConfigId"
        >
          <el-select
            v-model="importDialog.form.targetConfigId"
            filterable
          >
            <el-option
              v-for="config in importDialog.configs"
              :key="String(config.id)"
              :label="config.description || config.key"
              :value="config.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item
          label="快照描述"
          prop="description"
        >
          <el-input
            v-model="importDialog.form.description"
            maxlength="255"
          />
        </el-form-item>
        <el-form-item label="快照标签">
          <el-select
            v-model="importDialog.form.tags"
            multiple
          >
            <el-option
              v-for="tag in tagOptions"
              :key="tag.value"
              :label="tag.label"
              :value="tag.value"
            />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="importDialog.visible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="importDialog.saving"
          :disabled="!importDialog.targetHasPermission"
          @click="submitImport"
        >
          导入
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import {
  createSnapshot,
  deleteSnapshot,
  getCurrentSnapshot,
  getSnapshot,
  loadSnapshot,
  previewCreatingSnapshot,
} from '@/api/snapshots'
import {
  createImportIdempotencyKey,
  exportSnapshot,
  importSnapshot,
  publishSnapshot,
  unpublishSnapshot,
} from '@/api/snapshot-imports'
import { getMyPermissions } from '@/api/environments'
import DiffEditor from '@/components/DiffEditor'
import {
  normalizeSnapshotList,
  parseSnapshotContent,
  SNAPSHOT_TAG_OPTIONS,
  snapshotActionError,
  snapshotStatusLabel,
} from './model'

function emptyCreateDialog() {
  return {
    visible: false,
    saving: false,
    previewReady: false,
    currentContent: null,
    previewContent: null,
    form: { description: '', tags: [] },
  }
}

function emptyCompareDialog() {
  return {
    visible: false,
    ready: false,
    currentContent: null,
    snapshotContent: null,
  }
}

function emptyImportDialog() {
  return {
    visible: false,
    saving: false,
    loadingTarget: false,
    sourceSnapshotId: null,
    requestSignature: '',
    targetHasPermission: false,
    projects: [],
    configs: [],
    errorMessage: '',
    form: {
      targetEnvironmentId: null,
      targetProjectId: null,
      targetConfigId: null,
      conflictStrategy: 'FAIL',
      description: '',
      tags: [],
      idempotencyKey: '',
    },
  }
}

function requireSnapshot(reply, action) {
  if (!reply?.snapshot) {
    throw new TypeError(`${action}响应缺少 snapshot`)
  }
  return reply.snapshot
}

function configRows(reply) {
  if (!Array.isArray(reply?.list)) {
    throw new TypeError('目标配置列表响应缺少 list')
  }
  return reply.list.map((item) => {
    if (!item?.config) {
      throw new TypeError('目标配置列表项缺少 config')
    }
    return item.config
  })
}

export default {
  name: 'SnapshotsPanel',

  components: { DiffEditor },

  props: {
    projectId: { type: Number, required: true },
    configId: { type: Number, required: true },
  },

  data() {
    return {
      errorMessage: '',
      loading: false,
      snapshots: [],
      page: { page: 1, limit: 10, total: 0 },
      tagOptions: SNAPSHOT_TAG_OPTIONS,
      createDialog: emptyCreateDialog(),
      compareDialog: emptyCompareDialog(),
      importDialog: emptyImportDialog(),
      createRules: {
        description: [
          { required: true, message: '请输入快照描述', trigger: 'blur' },
          { min: 2, max: 255, message: '快照描述长度为 2 到 255 个字符', trigger: 'blur' },
        ],
        tags: [
          { type: 'array', required: true, min: 1, message: '请选择快照标签', trigger: 'change' },
        ],
      },
      importRules: {
        targetEnvironmentId: [
          { required: true, message: '请选择目标环境', trigger: 'change' },
        ],
        targetProjectId: [
          { required: true, message: '请选择目标项目', trigger: 'change' },
        ],
        targetConfigId: [
          { required: true, message: '请选择目标配置', trigger: 'change' },
        ],
        conflictStrategy: [
          { required: true, message: '请选择冲突策略', trigger: 'change' },
        ],
        description: [
          { required: true, message: '请输入快照描述', trigger: 'blur' },
          { min: 2, max: 255, message: '快照描述长度为 2 到 255 个字符', trigger: 'blur' },
        ],
      },
    }
  },

  computed: {
    environmentId() {
      return this.$store.state.environment.currentId
    },
    availableEnvironments() {
      return this.$store.state.environment.available
    },
    canWrite() {
      return this.$store.getters['environment/hasPermission']('snapshot:write')
    },
    canPublish() {
      return this.$store.getters['environment/hasPermission']('snapshot:publish')
    },
    canExport() {
      return this.$store.getters['environment/hasPermission']('snapshot:export')
    },
  },

  watch: {
    configId() {
      this.page.page = 1
      this.reload()
    },
  },

  created() {
    this.reload()
  },

  methods: {
    statusLabel: snapshotStatusLabel,
    async reload() {
      this.loading = true
      this.errorMessage = ''
      try {
        const reply = await this.$store.dispatch('configCenter/loadSnapshots', {
          environmentId: this.environmentId,
          projectId: this.projectId,
          configId: this.configId,
          filter: { page: { page: this.page.page, limit: this.page.limit } },
          force: true,
        })
        const normalized = normalizeSnapshotList(reply)
        this.snapshots = normalized.list
        this.page = {
          page: normalized.page.page,
          limit: normalized.page.limit,
          total: normalized.page.total,
        }
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '读取快照')
        this.$message.error(this.errorMessage)
      } finally {
        this.loading = false
      }
    },
    changePage(page) {
      this.page.page = page
      return this.reload()
    },
    changePageSize(limit) {
      this.page.page = 1
      this.page.limit = limit
      return this.reload()
    },
    async openCreate() {
      if (!this.canWrite) {
        throw new Error('当前用户没有创建快照权限')
      }
      this.createDialog = { ...emptyCreateDialog(), visible: true }
      try {
        const [currentReply, previewReply] = await Promise.all([
          getCurrentSnapshot(this.environmentId, this.configId),
          previewCreatingSnapshot(this.environmentId, this.configId),
        ])
        const current = requireSnapshot(currentReply, '当前快照')
        this.createDialog.currentContent = parseSnapshotContent(current.content)
        this.createDialog.previewContent = parseSnapshotContent(previewReply.content)
        this.createDialog.previewReady = true
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '读取快照预览')
        this.$message.error(this.errorMessage)
      }
    },
    clearCreate() {
      this.createDialog = emptyCreateDialog()
    },
    async createSnapshotRecord() {
      const valid = await new Promise((resolve) => {
        this.$refs.createForm.validate(resolve)
      })
      if (!valid) {
        return
      }
      this.createDialog.saving = true
      try {
        await createSnapshot(this.environmentId, {
          config_id: this.configId,
          project_id: this.projectId,
          description: this.createDialog.form.description,
          tags: this.createDialog.form.tags,
        })
        this.createDialog.visible = false
        this.$message.success('快照已创建')
        await this.reload()
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '创建快照')
        this.$message.error(this.errorMessage)
      } finally {
        this.createDialog.saving = false
      }
    },
    async openCompare(row) {
      this.compareDialog = { ...emptyCompareDialog(), visible: true }
      try {
        const [currentReply, snapshotReply] = await Promise.all([
          getCurrentSnapshot(this.environmentId, this.configId),
          getSnapshot(this.environmentId, row.id),
        ])
        const current = requireSnapshot(currentReply, '当前快照')
        const snapshot = requireSnapshot(snapshotReply, '快照详情')
        this.compareDialog.currentContent = parseSnapshotContent(current.content)
        this.compareDialog.snapshotContent = parseSnapshotContent(snapshot.content)
        this.compareDialog.ready = true
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '比较快照')
        this.$message.error(this.errorMessage)
      }
    },
    clearCompare() {
      this.compareDialog = emptyCompareDialog()
    },
    async restore(row) {
      if (!this.canWrite) {
        throw new Error('当前用户没有还原快照权限')
      }
      try {
        await this.$confirm('还原会覆盖尚未保存为快照的配置，是否继续？', '还原快照', {
          type: 'warning',
          confirmButtonText: '还原',
          cancelButtonText: '取消',
        })
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      try {
        await loadSnapshot(this.environmentId, row.id, this.configId)
        this.$message.success('快照已还原')
        this.$emit('changed')
        await this.reload()
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '还原快照')
        this.$message.error(this.errorMessage)
      }
    },
    async publish(row) {
      if (!this.canPublish) {
        throw new Error('当前用户没有发布快照权限')
      }
      try {
        await publishSnapshot(this.environmentId, row.id, row.version)
        this.$message.success('快照已发布')
        await this.reload()
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '发布快照')
        this.$message.error(this.errorMessage)
      }
    },
    async unpublish(row) {
      if (!this.canPublish) {
        throw new Error('当前用户没有下线快照权限')
      }
      try {
        await unpublishSnapshot(this.environmentId, row.id, row.version)
        this.$message.success('快照已下线')
        await this.reload()
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '下线快照')
        this.$message.error(this.errorMessage)
      }
    },
    async download(row) {
      if (!this.canExport) {
        throw new Error('当前用户没有导出快照权限')
      }
      try {
        const reply = await exportSnapshot(this.environmentId, row.id)
        const blob = new Blob([JSON.stringify(reply, null, 2)], {
          type: 'application/json',
        })
        const url = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.download = `kirby-snapshot-${row.id}.json`
        link.click()
        URL.revokeObjectURL(url)
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '导出源快照')
        this.$message.error(this.errorMessage)
      }
    },
    openImport(row) {
      if (!this.canExport) {
        throw new Error('当前用户没有导出源快照权限')
      }
      this.importDialog = {
        ...emptyImportDialog(),
        visible: true,
        sourceSnapshotId: row.id,
        form: {
          ...emptyImportDialog().form,
          description: row.description,
          tags: [...row.tags],
          idempotencyKey: createImportIdempotencyKey(),
        },
      }
    },
    clearImport() {
      this.importDialog = emptyImportDialog()
    },
    async loadTargetEnvironment(targetEnvironmentId) {
      this.importDialog.loadingTarget = true
      this.importDialog.errorMessage = ''
      this.importDialog.targetHasPermission = false
      this.importDialog.projects = []
      this.importDialog.configs = []
      this.importDialog.form.targetProjectId = null
      this.importDialog.form.targetConfigId = null
      try {
        const permissionReply = await getMyPermissions(targetEnvironmentId)
        if (!Array.isArray(permissionReply?.permissions)) {
          throw new TypeError('目标环境权限响应缺少 permissions')
        }
        const targetPermissions = new Set(permissionReply.permissions)
        if (
          !targetPermissions.has('snapshot:import') ||
          !targetPermissions.has('config:write')
        ) {
          this.importDialog.errorMessage =
            '当前用户没有目标环境的快照导入或配置写入权限。'
          return
        }
        this.importDialog.targetHasPermission = true
        const projectReply = await this.$store.dispatch('configCenter/loadProjects', {
          environmentId: targetEnvironmentId,
          filter: {},
          force: true,
        })
        if (!Array.isArray(projectReply?.list)) {
          throw new TypeError('目标项目列表响应缺少 list')
        }
        this.importDialog.projects = projectReply.list
      } catch (error) {
        this.importDialog.errorMessage = snapshotActionError(
          error,
          '读取目标环境权限和项目',
          '当前导入表单已保留。',
        )
      } finally {
        this.importDialog.loadingTarget = false
      }
    },
    async loadTargetConfigs(targetProjectId) {
      this.importDialog.configs = []
      this.importDialog.form.targetConfigId = null
      if (!targetProjectId) {
        return
      }
      try {
        const reply = await this.$store.dispatch('configCenter/loadConfigs', {
          environmentId: this.importDialog.form.targetEnvironmentId,
          projectId: targetProjectId,
          filter: {},
          force: true,
        })
        this.importDialog.configs = configRows(reply)
      } catch (error) {
        this.importDialog.errorMessage = snapshotActionError(
          error,
          '读取目标配置',
          '当前导入表单已保留。',
        )
      }
    },
    async submitImport() {
      if (!this.importDialog.targetHasPermission) {
        throw new Error('目标环境没有快照导入权限')
      }
      const valid = await new Promise((resolve) => {
        this.$refs.importForm.validate(resolve)
      })
      if (!valid) {
        return
      }
      const form = this.importDialog.form
      if (form.conflictStrategy === 'REPLACE' && !form.targetConfigId) {
        this.importDialog.errorMessage = '替换策略必须选择目标配置。'
        return
      }
      this.importDialog.saving = true
      this.importDialog.errorMessage = ''
      try {
        const request = {
          source_environment_id: this.environmentId,
          source_snapshot_id: this.importDialog.sourceSnapshotId,
          target_project_id: form.targetProjectId,
          description: form.description,
          tags: form.tags,
          conflict_strategy: form.conflictStrategy,
        }
        if (form.conflictStrategy === 'REPLACE') {
          request.target_config_id = form.targetConfigId
        }
        const requestSignature = JSON.stringify({
          ...request,
          target_environment_id: form.targetEnvironmentId,
        })
        if (
          this.importDialog.requestSignature &&
          this.importDialog.requestSignature !== requestSignature
        ) {
          form.idempotencyKey = createImportIdempotencyKey()
        }
        this.importDialog.requestSignature = requestSignature
        request.idempotency_key = form.idempotencyKey
        const reply = await importSnapshot(form.targetEnvironmentId, request)
        if (!reply?.snapshot) {
          throw new TypeError('快照导入响应缺少 snapshot')
        }
        this.$message.success(reply.replayed ? '已返回上次导入结果' : '快照已导入')
        this.importDialog.visible = false
      } catch (error) {
        this.importDialog.errorMessage = snapshotActionError(
          error,
          '从源环境导出或向目标环境导入',
          '当前导入表单已保留，可重试同一请求。',
        )
        this.$message.error(this.importDialog.errorMessage)
      } finally {
        this.importDialog.saving = false
      }
    },
    async remove(row) {
      if (!this.canWrite) {
        throw new Error('当前用户没有删除快照权限')
      }
      try {
        await this.$confirm(`确认删除快照“${row.description}”吗？`, '删除快照', {
          type: 'warning',
          confirmButtonText: '删除',
          cancelButtonText: '取消',
        })
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      try {
        await deleteSnapshot(this.environmentId, row.id)
        this.$message.success('快照已删除')
        await this.reload()
      } catch (error) {
        this.errorMessage = snapshotActionError(error, '删除快照')
        this.$message.error(this.errorMessage)
      }
    },
  },
}
</script>

<style scoped>
.snapshots-panel__toolbar,
.snapshots-panel__pagination {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin: 16px 0;
}

.snapshots-panel__toolbar p,
.snapshots-panel__hint {
  margin: 0;
  color: #6b7280;
}

.snapshots-panel__pagination {
  justify-content: flex-end;
}

.snapshots-panel__tag {
  margin: 2px 4px 2px 0;
}

.snapshots-panel__diff {
  min-height: 420px;
  margin-top: 10px;
}

.snapshots-panel__danger {
  color: #f56c6c;
}
</style>

// web/src/features/config-center/snapshots/SnapshotsPanel.tsx
import { DownloadOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Form, Input, Modal, Pagination, Select, Space, Table, Tag } from 'antd'
import { useRef, useState } from 'react'

import { getMyPermissions } from '@/api/environments'
import { listConfigs } from '@/api/configs'
import { listProjects } from '@/api/projects'
import { createImportIdempotencyKey, exportSnapshot, importSnapshot, publishSnapshot, unpublishSnapshot, type ImportConflictStrategy } from '@/api/snapshot-imports'
import { createSnapshot, deleteSnapshot, getCurrentSnapshot, getSnapshot, listSnapshots, loadSnapshot, previewCreatingSnapshot } from '@/api/snapshots'
import type { Identifier } from '@/api/types'
import { queryKeys } from '@/app/query-keys'
import { useEnvironment } from '@/auth/environment-state'
import DiffEditor from '@/components/DiffEditor/DiffEditor'
import { normalizeSnapshotList, parseSnapshotContent, SNAPSHOT_TAG_OPTIONS, snapshotActionError, snapshotStatusLabel, type SnapshotStatus } from '@/domain/snapshots'
import { normalizeConfigList, type ConfigSummary, type Project } from '../queries'
import { requireList } from '@/features/system/errors'
import { nextImportRequestIdentity } from './import-request'

type SnapshotRow = Record<string, unknown> & {
  id: Identifier
  description: string
  version: number
  createdBy?: string
  createdAt?: string
  tags: string[]
  status: SnapshotStatus
}
type CreateForm = { description: string; tags: string[] }
type ImportForm = {
  targetEnvironmentId: Identifier
  targetProjectId: Identifier
  targetConfigId?: Identifier
  conflictStrategy: ImportConflictStrategy
  description: string
  tags: string[]
}
type Props = { projectId: Identifier; configId: Identifier; onChanged?: () => void }

function requireSnapshot(reply: unknown, action: string): Record<string, unknown> {
  if (typeof reply !== 'object' || reply === null || !('snapshot' in reply) || typeof reply.snapshot !== 'object' || reply.snapshot === null) {
    throw new TypeError(`${action}响应缺少 snapshot`)
  }
  return reply.snapshot as Record<string, unknown>
}

function contentOf(snapshot: Record<string, unknown>): unknown {
  if (typeof snapshot.content !== 'string') throw new TypeError('快照内容必须是非空 JSON 字符串')
  return parseSnapshotContent(snapshot.content)
}

export default function SnapshotsPanel({ projectId, configId, onChanged }: Props) {
  const { message, modal } = App.useApp()
  const environment = useEnvironment()
  const queryClient = useQueryClient()
  const [page, setPage] = useState({ page: 1, limit: 10 })
  const [createForm] = Form.useForm<CreateForm>()
  const [importForm] = Form.useForm<ImportForm>()
  const [createOpen, setCreateOpen] = useState(false)
  const [createDiff, setCreateDiff] = useState<{ current: unknown; preview: unknown } | null>(null)
  const [compareOpen, setCompareOpen] = useState(false)
  const [compareDiff, setCompareDiff] = useState<{ current: unknown; snapshot: unknown } | null>(null)
  const [importOpen, setImportOpen] = useState(false)
  const [sourceSnapshot, setSourceSnapshot] = useState<SnapshotRow | null>(null)
  const [targetAllowed, setTargetAllowed] = useState(false)
  const [targetLoading, setTargetLoading] = useState(false)
  const [targetProjects, setTargetProjects] = useState<Project[]>([])
  const [targetConfigs, setTargetConfigs] = useState<ConfigSummary[]>([])
  const [actionError, setActionError] = useState<unknown>(null)
  const [importError, setImportError] = useState('')
  const importRequest = useRef({ signature: '', key: '' })
  const canWrite = environment.hasPermission('snapshot:write')
  const canPublish = environment.hasPermission('snapshot:publish')
  const canExport = environment.hasPermission('snapshot:export')
  const snapshots = useQuery({
    queryKey: environment.currentId === null ? ['environment', 'none', 'snapshots'] : queryKeys.snapshots(environment.currentId, projectId, configId, { page }),
    queryFn: async () => {
      if (environment.currentId === null) throw new Error('当前没有可用环境')
      const normalized = normalizeSnapshotList(await listSnapshots(environment.currentId, { project_id: projectId, config_id: configId, page }))
      return { list: normalized.list as SnapshotRow[], page: { page: Number(normalized.page.page), limit: Number(normalized.page.limit), total: Number(normalized.page.total) } }
    },
    enabled: environment.currentId !== null,
  })
  const refresh = () => environment.currentId === null ? Promise.resolve() : queryClient.invalidateQueries({ queryKey: queryKeys.snapshots(environment.currentId, projectId, configId) })
  const create = useMutation({ mutationFn: (values: CreateForm) => { if (environment.currentId === null) throw new Error('当前没有可用环境'); return createSnapshot(environment.currentId, { config_id: configId, project_id: projectId, description: values.description, tags: values.tags }) }, onSuccess: refresh })
  const transfer = useMutation({
    mutationFn: async ({ operation, row }: { operation: 'restore' | 'publish' | 'unpublish' | 'delete'; row: SnapshotRow }) => {
      if (environment.currentId === null) throw new Error('当前没有可用环境')
      if (operation === 'restore') return loadSnapshot(environment.currentId, row.id, configId)
      if (operation === 'publish') return publishSnapshot(environment.currentId, row.id, row.version)
      if (operation === 'unpublish') return unpublishSnapshot(environment.currentId, row.id, row.version)
      return deleteSnapshot(environment.currentId, row.id)
    },
    onSuccess: refresh,
  })
  const importing = useMutation({
    mutationFn: ({ targetEnvironmentId, request }: { targetEnvironmentId: Identifier; request: Parameters<typeof importSnapshot>[1] }) => importSnapshot(targetEnvironmentId, request),
  })

  const openCreate = async () => {
    if (!canWrite) throw new Error('当前用户没有创建快照权限')
    if (environment.currentId === null) throw new Error('当前没有可用环境')
    setActionError(null); setCreateDiff(null); createForm.setFieldsValue({ description: '', tags: [] }); setCreateOpen(true)
    try {
      const [currentReply, previewReply] = await Promise.all([getCurrentSnapshot(environment.currentId, configId), previewCreatingSnapshot(environment.currentId, configId)])
      const current = requireSnapshot(currentReply, '当前快照')
      if (typeof previewReply.content !== 'string') throw new TypeError('快照预览响应缺少 content')
      setCreateDiff({ current: contentOf(current), preview: parseSnapshotContent(previewReply.content) })
    } catch (error: unknown) { setActionError(error) }
  }
  const submitCreate = async (values: CreateForm) => {
    setActionError(null)
    try { await create.mutateAsync(values); setCreateOpen(false); setCreateDiff(null); createForm.resetFields(); void message.success('快照已创建') } catch (error: unknown) { setActionError(error) }
  }
  const openCompare = async (row: SnapshotRow) => {
    if (environment.currentId === null) throw new Error('当前没有可用环境')
    setActionError(null); setCompareDiff(null); setCompareOpen(true)
    try { const [currentReply, snapshotReply] = await Promise.all([getCurrentSnapshot(environment.currentId, configId), getSnapshot(environment.currentId, row.id)]); setCompareDiff({ current: contentOf(requireSnapshot(currentReply, '当前快照')), snapshot: contentOf(requireSnapshot(snapshotReply, '快照详情')) }) } catch (error: unknown) { setActionError(error) }
  }
  const execute = async (operation: 'restore' | 'publish' | 'unpublish' | 'delete', row: SnapshotRow) => {
    setActionError(null)
    try { await transfer.mutateAsync({ operation, row }); if (operation === 'restore') onChanged?.(); void message.success({ restore: '快照已还原', publish: '快照已发布', unpublish: '快照已下线', delete: '快照已删除' }[operation]) } catch (error: unknown) { setActionError(error); throw error }
  }
  const confirmRestore = (row: SnapshotRow) => modal.confirm({ title: '还原快照', content: '还原会覆盖尚未保存为快照的配置，是否继续？', okText: '还原', onOk: () => execute('restore', row) })
  const confirmDelete = (row: SnapshotRow) => modal.confirm({ title: '删除快照', content: `确认删除快照“${row.description}”吗？`, okText: '删除', okButtonProps: { danger: true }, onOk: () => execute('delete', row) })
  const download = async (row: SnapshotRow) => {
    if (!canExport) throw new Error('当前用户没有导出快照权限')
    if (environment.currentId === null) throw new Error('当前没有可用环境')
    setActionError(null)
    try {
      const reply = await exportSnapshot(environment.currentId, row.id)
      const url = URL.createObjectURL(new Blob([JSON.stringify(reply, null, 2)], { type: 'application/json' }))
      try { const link = document.createElement('a'); link.href = url; link.download = `kirby-snapshot-${row.id}.json`; link.click() } finally { URL.revokeObjectURL(url) }
    } catch (error: unknown) { setActionError(error) }
  }
  const openImport = (row: SnapshotRow) => {
    if (!canExport) throw new Error('当前用户没有导出源快照权限')
    const key = createImportIdempotencyKey()
    importRequest.current = { signature: '', key }
    setSourceSnapshot(row); setTargetAllowed(false); setTargetProjects([]); setTargetConfigs([]); setImportError('')
    importForm.setFieldsValue({ conflictStrategy: 'FAIL', description: row.description, tags: [...row.tags] })
    setImportOpen(true)
  }
  const loadTargetEnvironment = async (targetEnvironmentId: Identifier) => {
    setTargetLoading(true); setImportError(''); setTargetAllowed(false); setTargetProjects([]); setTargetConfigs([]); importForm.resetFields(['targetProjectId', 'targetConfigId'])
    try {
      const permissions = await getMyPermissions(targetEnvironmentId)
      if (!Array.isArray(permissions.permissions)) throw new TypeError('目标环境权限响应缺少 permissions')
      const declared = new Set(permissions.permissions)
      if (!declared.has('snapshot:import') || !declared.has('config:write')) { setImportError('当前用户没有目标环境的快照导入或配置写入权限。'); return }
      setTargetAllowed(true)
      setTargetProjects(requireList<Project>(await listProjects(targetEnvironmentId, {}), 'target project list'))
    } catch (error: unknown) { setImportError(snapshotActionError(error, '读取目标环境权限和项目', '当前导入表单已保留。')) } finally { setTargetLoading(false) }
  }
  const loadTargetConfigs = async (targetProjectId: Identifier) => {
    setTargetConfigs([]); setImportError(''); importForm.setFieldValue('targetConfigId', undefined)
    const targetEnvironmentId = importForm.getFieldValue('targetEnvironmentId')
    try { setTargetConfigs(normalizeConfigList(await listConfigs(targetEnvironmentId, { project_id: targetProjectId }))) } catch (error: unknown) { setImportError(snapshotActionError(error, '读取目标配置', '当前导入表单已保留。')) }
  }
  const submitImport = async (values: ImportForm) => {
    if (!targetAllowed) throw new Error('目标环境没有快照导入权限')
    if (!sourceSnapshot || environment.currentId === null) throw new Error('源快照尚未选择')
    if (values.conflictStrategy === 'REPLACE' && !values.targetConfigId) { setImportError('替换策略必须选择目标配置。'); return }
    const base = { source_environment_id: environment.currentId, source_snapshot_id: sourceSnapshot.id, target_project_id: values.targetProjectId, description: values.description, tags: values.tags, conflict_strategy: values.conflictStrategy, ...(values.conflictStrategy === 'REPLACE' ? { target_config_id: values.targetConfigId } : {}) }
    const signature = JSON.stringify({ ...base, target_environment_id: values.targetEnvironmentId })
    importRequest.current = nextImportRequestIdentity(importRequest.current, signature, createImportIdempotencyKey)
    setImportError('')
    try {
      const reply = await importing.mutateAsync({ targetEnvironmentId: values.targetEnvironmentId, request: { ...base, idempotency_key: importRequest.current.key } })
      if (!reply.snapshot) throw new TypeError('快照导入响应缺少 snapshot')
      void message.success(reply.replayed ? '已返回上次导入结果' : '快照已导入')
      setImportOpen(false); setSourceSnapshot(null); importForm.resetFields()
    } catch (error: unknown) { setImportError(snapshotActionError(error, '从源环境导出或向目标环境导入', '当前导入表单已保留，可重试同一请求。')) }
  }

  const error = actionError ?? snapshots.error
  const conflictStrategy = Form.useWatch('conflictStrategy', importForm)
  return (
    <section aria-label="快照管理" className="resource-panel">
      {error ? <Alert className="management-alert" type="error" showIcon message={snapshotActionError(error, actionError ? '执行快照操作' : '读取快照')} /> : null}
      <header className="resource-toolbar"><p>快照用于比较、还原、发布和跨环境复用配置。</p><Space><Button size="small" icon={<ReloadOutlined />} loading={snapshots.isFetching} onClick={() => void snapshots.refetch()}>刷新</Button>{canWrite ? <Button type="primary" size="small" icon={<PlusOutlined />} onClick={() => void openCreate()}>创建快照</Button> : null}</Space></header>
      <Table<SnapshotRow> rowKey="id" loading={snapshots.isLoading} dataSource={snapshots.data?.list ?? []} locale={{ emptyText: '当前配置还没有快照' }} pagination={false} scroll={{ x: 1180 }} columns={[
        { title: 'ID', dataIndex: 'id', width: 80 }, { title: '描述', dataIndex: 'description', width: 220 }, { title: '标签', width: 180, render: (_, row) => row.tags.map((tag) => <Tag key={tag}>{tag}</Tag>) }, { title: '状态', width: 110, render: (_, row) => <Tag color={row.status === 'RELEASED' ? 'green' : 'default'}>{snapshotStatusLabel(row.status)}</Tag> }, { title: '创建人', dataIndex: 'createdBy', width: 130 }, { title: '创建时间', dataIndex: 'createdAt', width: 190 },
        { title: '操作', width: 430, fixed: 'right', render: (_, row) => <div className="table-actions"><Button type="link" onClick={() => void openCompare(row)}>比较</Button>{canWrite ? <Button type="link" onClick={() => confirmRestore(row)}>还原</Button> : null}{canPublish && row.status === 'UNRELEASED' ? <Button type="link" onClick={() => void execute('publish', row).catch(() => undefined)}>发布</Button> : null}{canPublish && row.status === 'RELEASED' ? <Button type="link" onClick={() => void execute('unpublish', row).catch(() => undefined)}>下线</Button> : null}{canExport ? <Button type="link" icon={<DownloadOutlined />} onClick={() => void download(row)}>导出</Button> : null}{canExport ? <Button type="link" onClick={() => openImport(row)}>导入到环境</Button> : null}{canWrite && row.status === 'UNRELEASED' ? <Button type="link" danger onClick={() => confirmDelete(row)}>删除</Button> : null}</div> },
      ]} />
      <Pagination className="resource-pagination" current={snapshots.data?.page.page || page.page} pageSize={snapshots.data?.page.limit || page.limit} total={snapshots.data?.page.total || 0} showSizeChanger pageSizeOptions={[10, 20, 50, 100]} onChange={(nextPage, limit) => setPage({ page: limit === page.limit ? nextPage : 1, limit })} />
      <Modal title="创建快照" open={createOpen} width={1100} confirmLoading={create.isPending} okText="创建" onCancel={() => { setCreateOpen(false); setCreateDiff(null); createForm.resetFields() }} onOk={() => createForm.submit()} destroyOnHidden>
        <Form form={createForm} layout="vertical" onFinish={submitCreate} preserve={false}><Form.Item label="快照标签" name="tags" rules={[{ required: true, type: 'array', min: 1, message: '请选择快照标签' }]}><Select mode="multiple" options={[...SNAPSHOT_TAG_OPTIONS]} /></Form.Item><Form.Item label="快照描述" name="description" rules={[{ required: true, message: '请输入快照描述' }, { min: 2, max: 255, message: '快照描述长度为 2 到 255 个字符' }]}><Input.TextArea rows={3} maxLength={255} showCount /></Form.Item><p className="secondary-text">左侧是当前配置，右侧是待创建快照。</p>{createDiff ? <DiffEditor leftValue={createDiff.current} rightValue={createDiff.preview} /> : <p>正在读取快照预览…</p>}</Form>
      </Modal>
      <Modal title="比较快照" open={compareOpen} width={1100} footer={null} onCancel={() => { setCompareOpen(false); setCompareDiff(null) }} destroyOnHidden><p className="secondary-text">左侧是当前配置，右侧是所选快照。</p>{compareDiff ? <DiffEditor leftValue={compareDiff.current} rightValue={compareDiff.snapshot} /> : <p>正在读取比较内容…</p>}</Modal>
      <Modal title="导入快照到目标环境" open={importOpen} width={680} confirmLoading={importing.isPending} okText="导入" okButtonProps={{ disabled: !targetAllowed }} onCancel={() => { setImportOpen(false); setSourceSnapshot(null); setImportError(''); importForm.resetFields() }} onOk={() => importForm.submit()} destroyOnHidden>
        {importError ? <Alert className="management-alert" type="error" showIcon message={importError} /> : null}
        <Form form={importForm} layout="vertical" onFinish={submitImport} preserve={false}><Form.Item label="源快照"><Input value={`环境 ${environment.currentId} / 快照 ${sourceSnapshot?.id ?? ''}`} disabled /></Form.Item><Form.Item label="目标环境" name="targetEnvironmentId" rules={[{ required: true, message: '请选择目标环境' }]}><Select loading={targetLoading} options={environment.available.map((item) => ({ label: item.name, value: item.id, disabled: !item.enabled }))} onChange={(value) => void loadTargetEnvironment(value)} /></Form.Item><Form.Item label="目标项目" name="targetProjectId" rules={[{ required: true, message: '请选择目标项目' }]}><Select disabled={!targetAllowed} options={targetProjects.map((item) => ({ label: item.name, value: item.id }))} onChange={(value) => void loadTargetConfigs(value)} /></Form.Item><Form.Item label="冲突策略" name="conflictStrategy" rules={[{ required: true, message: '请选择冲突策略' }]}><Select options={[{ label: '冲突时报错并创建新配置', value: 'FAIL' }, { label: '替换指定配置', value: 'REPLACE' }]} /></Form.Item>{conflictStrategy === 'REPLACE' ? <Form.Item label="目标配置" name="targetConfigId" rules={[{ required: true, message: '请选择目标配置' }]}><Select options={targetConfigs.map((item) => ({ label: item.description || item.key, value: item.id }))} /></Form.Item> : null}<Form.Item label="快照描述" name="description" rules={[{ required: true, message: '请输入快照描述' }, { min: 2, max: 255, message: '快照描述长度为 2 到 255 个字符' }]}><Input maxLength={255} /></Form.Item><Form.Item label="快照标签" name="tags"><Select mode="multiple" options={[...SNAPSHOT_TAG_OPTIONS]} /></Form.Item></Form>
      </Modal>
    </section>
  )
}
