// web/src/features/system/RolesPage.vue
<template>
  <section class="management-card">
    <header class="management-card__header">
      <div>
        <h2>角色与权限</h2>
        <p>权限清单由后端返回。页面不会补充未声明权限。</p>
      </div>
      <el-button
        v-if="systemAdmin"
        type="primary"
        @click="openCreate"
      >
        新建角色
      </el-button>
    </header>

    <el-alert
      v-if="errorMessage"
      class="management-card__alert"
      :title="errorMessage"
      type="error"
      :closable="false"
      show-icon
    />
    <el-alert
      v-if="!systemAdmin"
      title="只有系统管理员可以修改全局角色与权限"
      type="warning"
      :closable="false"
      show-icon
    />

    <el-table
      v-else
      v-loading="loading"
      :data="roles"
      empty-text="暂无角色"
    >
      <el-table-column
        prop="name"
        label="名称"
        min-width="140"
      />
      <el-table-column
        prop="key"
        label="标识"
        min-width="140"
      />
      <el-table-column
        prop="description"
        label="说明"
        min-width="220"
      />
      <el-table-column
        label="权限数"
        width="90"
      >
        <template #default="{ row }">
          {{ Array.isArray(row.permissions) ? row.permissions.length : 0 }}
        </template>
      </el-table-column>
      <el-table-column
        label="类型"
        width="100"
      >
        <template #default="{ row }">
          <el-tag :type="row.builtin ? 'info' : ''">
            {{ row.builtin ? '内置' : '自定义' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column
        label="操作"
        width="250"
        fixed="right"
      >
        <template #default="{ row }">
          <el-button
            type="text"
            @click="openEdit(row)"
          >
            编辑
          </el-button>
          <el-button
            type="text"
            @click="openPermissions(row)"
          >
            配置权限
          </el-button>
          <el-button
            v-if="!row.builtin"
            type="text"
            class="danger-action"
            @click="removeRole(row)"
          >
            删除
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      :title="editing ? '编辑角色' : '新建角色'"
      :visible.sync="roleDialogVisible"
      width="520px"
      :close-on-click-modal="false"
    >
      <el-form
        ref="roleForm"
        :model="form"
        :rules="rules"
        label-position="top"
      >
        <el-form-item
          label="角色标识"
          prop="key"
        >
          <el-input
            v-model.trim="form.key"
            :disabled="editing"
          />
        </el-form-item>
        <el-form-item
          label="名称"
          prop="name"
        >
          <el-input v-model.trim="form.name" />
        </el-form-item>
        <el-form-item
          label="说明"
          prop="description"
        >
          <el-input
            v-model="form.description"
            type="textarea"
            :rows="3"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="roleDialogVisible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="saving"
          @click="saveRole"
        >
          保存
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      :title="permissionRole ? `配置“${permissionRole.name}”的权限` : '配置权限'"
      :visible.sync="permissionDialogVisible"
      width="660px"
      :close-on-click-modal="false"
    >
      <el-alert
        v-if="permissions.length === 0"
        title="后端没有返回可分配权限"
        type="warning"
        :closable="false"
        show-icon
      />
      <el-checkbox-group
        v-else
        v-model="selectedPermissionIds"
        class="permission-list"
        aria-label="权限清单"
      >
        <div
          v-for="permission in permissions"
          :key="String(permission.id)"
          class="permission-list__item"
        >
          <el-checkbox :label="permission.id">
            {{ permission.name }}（{{ permission.key }}）
          </el-checkbox>
          <p class="permission-list__description">
            {{ permission.description || '无说明' }}
          </p>
        </div>
      </el-checkbox-group>
      <template #footer>
        <el-button @click="permissionDialogVisible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="savingPermissions"
          :disabled="permissions.length === 0"
          @click="savePermissions"
        >
          保存权限
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import {
  createRole,
  deleteRole,
  listPermissions,
  listRoles,
  updateRole,
  updateRolePermissions,
} from '@/api/roles'

import { actionErrorMessage, requireList } from './errors'

function emptyRoleForm() {
  return {
    id: null,
    key: '',
    name: '',
    description: '',
    version: 0,
  }
}

export default {
  name: 'RolesPage',

  data() {
    return {
      roles: [],
      permissions: [],
      selectedPermissionIds: [],
      permissionRole: null,
      loading: false,
      saving: false,
      savingPermissions: false,
      errorMessage: '',
      roleDialogVisible: false,
      permissionDialogVisible: false,
      form: emptyRoleForm(),
      rules: {
        key: [
          { required: true, message: '请输入角色标识', trigger: 'blur' },
          {
            pattern: /^[a-z][a-z0-9_:.-]*$/,
            message: '角色标识格式不正确',
            trigger: 'blur',
          },
        ],
        name: [{ required: true, message: '请输入角色名称', trigger: 'blur' }],
        description: [
          { max: 255, message: '说明不能超过 255 个字符', trigger: 'blur' },
        ],
      },
    }
  },

  computed: {
    systemAdmin() {
      return this.$store.getters['session/systemAdmin']
    },
    editing() {
      return this.form.id !== null
    },
  },

  created() {
    if (this.systemAdmin) {
      this.load()
    }
  },

  methods: {
    async load() {
      this.loading = true
      this.errorMessage = ''
      try {
        const [roleReply, permissionReply] = await Promise.all([
          listRoles(),
          listPermissions(),
        ])
        this.roles = requireList(roleReply, 'role list')
        this.permissions = requireList(permissionReply, 'permission list')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '读取角色与权限')
      } finally {
        this.loading = false
      }
    },
    openCreate() {
      this.form = emptyRoleForm()
      this.errorMessage = ''
      this.roleDialogVisible = true
      this.$nextTick(() => this.$refs.roleForm?.clearValidate())
    },
    openEdit(role) {
      this.form = {
        id: role.id,
        key: role.key,
        name: role.name,
        description: role.description || '',
        version: role.version,
      }
      this.errorMessage = ''
      this.roleDialogVisible = true
      this.$nextTick(() => this.$refs.roleForm?.clearValidate())
    },
    async saveRole() {
      await this.$refs.roleForm.validate()
      this.saving = true
      this.errorMessage = ''
      try {
        if (this.editing) {
          await updateRole(this.form.id, {
            name: this.form.name,
            description: this.form.description,
            version: this.form.version,
          })
        } else {
          await createRole({
            key: this.form.key,
            name: this.form.name,
            description: this.form.description,
          })
        }
        this.roleDialogVisible = false
        await this.load()
        this.$message.success('角色已保存')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '保存角色')
      } finally {
        this.saving = false
      }
    },
    openPermissions(role) {
      this.permissionRole = role
      this.selectedPermissionIds = Array.isArray(role.permissions)
        ? role.permissions.map((permission) => permission.id)
        : []
      this.errorMessage = ''
      this.permissionDialogVisible = true
    },
    async savePermissions() {
      if (!this.permissionRole) {
        return
      }
      this.savingPermissions = true
      this.errorMessage = ''
      try {
        await updateRolePermissions(
          this.permissionRole.id,
          this.selectedPermissionIds,
        )
        this.permissionDialogVisible = false
        await this.load()
        this.$message.success('角色权限已更新')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '保存角色权限')
      } finally {
        this.savingPermissions = false
      }
    },
    async removeRole(role) {
      try {
        await this.$confirm(
          `确认删除角色“${role.name}”吗？仍被成员使用的角色不能删除。`,
          '确认删除',
          { type: 'warning' },
        )
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      this.errorMessage = ''
      try {
        await deleteRole(role.id)
        await this.load()
        this.$message.success('角色已删除')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '删除角色')
      }
    },
  },
}
</script>

<style scoped src="./management-card.css"></style>

<style scoped>
.danger-action {
  color: #dc2626;
}
</style>

// web/src/features/system/RolesPage.tsx
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Checkbox, Form, Input, Modal, Table, Tag } from 'antd'
import { useState } from 'react'

import { createRole, deleteRole, updateRole, updateRolePermissions } from '@/api/roles'
import type { Identifier } from '@/api/types'
import { queryKeys } from '@/app/query-keys'
import { useAuth } from '@/auth/auth-state'
import { actionErrorMessage } from './errors'
import { type Role, usePermissionsQuery, useRolesQuery } from './queries'

type RoleForm = { key: string; name: string; description: string }

export default function RolesPage() {
  const { message, modal } = App.useApp()
  const { systemAdmin } = useAuth()
  const queryClient = useQueryClient()
  const roles = useRolesQuery(systemAdmin)
  const permissions = usePermissionsQuery(systemAdmin)
  const [form] = Form.useForm<RoleForm>()
  const [editing, setEditing] = useState<Role | null>(null)
  const [permissionRole, setPermissionRole] = useState<Role | null>(null)
  const [selectedPermissionIds, setSelectedPermissionIds] = useState<Identifier[]>([])
  const [roleOpen, setRoleOpen] = useState(false)
  const [permissionOpen, setPermissionOpen] = useState(false)
  const [actionError, setActionError] = useState<unknown>(null)
  const refreshRoles = () => queryClient.invalidateQueries({ queryKey: queryKeys.roles })
  const save = useMutation({
    mutationFn: (values: RoleForm) => editing
      ? updateRole(editing.id, { name: values.name, description: values.description, version: editing.version })
      : createRole(values),
    onSuccess: refreshRoles,
  })
  const savePermissions = useMutation({
    mutationFn: () => {
      if (!permissionRole) throw new Error('没有选择角色')
      return updateRolePermissions(permissionRole.id, selectedPermissionIds)
    },
    onSuccess: refreshRoles,
  })
  const remove = useMutation({ mutationFn: deleteRole, onSuccess: refreshRoles })

  const closeRole = () => {
    setRoleOpen(false)
    setEditing(null)
    form.resetFields()
  }
  const showCreate = () => {
    setActionError(null)
    setEditing(null)
    form.setFieldsValue({ key: '', name: '', description: '' })
    setRoleOpen(true)
  }
  const showEdit = (role: Role) => {
    setActionError(null)
    setEditing(role)
    form.setFieldsValue({ key: role.key, name: role.name, description: role.description ?? '' })
    setRoleOpen(true)
  }
  const submit = async (values: RoleForm) => {
    setActionError(null)
    try {
      await save.mutateAsync(values)
      closeRole()
      void message.success('角色已保存')
    } catch (error: unknown) {
      setActionError(error)
    }
  }
  const showPermissions = (role: Role) => {
    setActionError(null)
    setPermissionRole(role)
    setSelectedPermissionIds((role.permissions ?? []).map((permission) => permission.id))
    setPermissionOpen(true)
  }
  const submitPermissions = async () => {
    setActionError(null)
    try {
      await savePermissions.mutateAsync()
      setPermissionOpen(false)
      setPermissionRole(null)
      setSelectedPermissionIds([])
      void message.success('角色权限已更新')
    } catch (error: unknown) {
      setActionError(error)
    }
  }
  const confirmRemove = (role: Role) => modal.confirm({
    title: '确认删除',
    content: `确认删除角色“${role.name}”吗？仍被成员使用的角色不能删除。`,
    okButtonProps: { danger: true },
    okText: '删除',
    onOk: async () => {
      setActionError(null)
      try {
        await remove.mutateAsync(role.id)
        void message.success('角色已删除')
      } catch (error: unknown) {
        setActionError(error)
        throw error
      }
    },
  })

  const queryError = roles.error ?? permissions.error
  return (
    <section className="management-panel">
      <header className="management-header">
        <div><h2>角色与权限</h2><p>权限清单由后端返回。页面不会补充未声明权限。</p></div>
        {systemAdmin ? <Button type="primary" onClick={showCreate}>新建角色</Button> : null}
      </header>
      {actionError ?? queryError ? <Alert className="management-alert" type="error" showIcon message={actionErrorMessage(actionError ?? queryError, actionError ? '执行角色操作' : '读取角色与权限')} /> : null}
      {!systemAdmin ? <Alert type="warning" showIcon message="只有系统管理员可以修改全局角色与权限" /> : (
        <Table<Role> rowKey="id" loading={roles.isLoading || permissions.isLoading} dataSource={roles.data ?? []} locale={{ emptyText: '暂无角色' }} pagination={false} scroll={{ x: 900 }} columns={[
          { title: '名称', dataIndex: 'name', width: 170 },
          { title: '标识', dataIndex: 'key', width: 170 },
          { title: '说明', dataIndex: 'description' },
          { title: '权限数', width: 90, render: (_, role) => role.permissions?.length ?? 0 },
          { title: '类型', width: 100, render: (_, role) => <Tag>{role.builtin ? '内置' : '自定义'}</Tag> },
          { title: '操作', width: 250, fixed: 'right', render: (_, role) => <div className="table-actions"><Button type="link" onClick={() => showEdit(role)}>编辑</Button><Button type="link" onClick={() => showPermissions(role)}>配置权限</Button>{!role.builtin ? <Button type="link" danger onClick={() => confirmRemove(role)}>删除</Button> : null}</div> },
        ]} />
      )}
      <Modal title={editing ? '编辑角色' : '新建角色'} open={roleOpen} width={520} confirmLoading={save.isPending} onCancel={closeRole} onOk={() => form.submit()} afterClose={() => form.resetFields()} destroyOnHidden>
        <Form form={form} layout="vertical" onFinish={submit} preserve={false}>
          <Form.Item label="角色标识" name="key" rules={[{ required: true, message: '请输入角色标识' }, { pattern: /^[a-z][a-z0-9_:.-]*$/, message: '角色标识格式不正确' }]}><Input disabled={Boolean(editing)} /></Form.Item>
          <Form.Item label="名称" name="name" rules={[{ required: true, message: '请输入角色名称' }]}><Input /></Form.Item>
          <Form.Item label="说明" name="description" rules={[{ max: 255, message: '说明不能超过 255 个字符' }]}><Input.TextArea rows={3} /></Form.Item>
        </Form>
      </Modal>
      <Modal
        title={permissionRole ? `配置“${permissionRole.name}”的权限` : '配置权限'}
        open={permissionOpen}
        width={660}
        confirmLoading={savePermissions.isPending}
        okButtonProps={{ disabled: !permissions.data?.length }}
        okText="保存权限"
        onCancel={() => { setPermissionOpen(false); setPermissionRole(null); setSelectedPermissionIds([]) }}
        onOk={submitPermissions}
        destroyOnHidden
      >
        {!permissions.data?.length ? <Alert type="warning" showIcon message="后端没有返回可分配权限" /> : (
          <Checkbox.Group aria-label="权限清单" className="permission-list" value={selectedPermissionIds} onChange={(values) => setSelectedPermissionIds(values)}>
            {permissions.data.map((permission) => (
              <label className="permission-item" key={permission.id}>
                <Checkbox value={permission.id}>{permission.name}（{permission.key}）</Checkbox>
                <span>{permission.description || '无说明'}</span>
              </label>
            ))}
          </Checkbox.Group>
        )}
      </Modal>
    </section>
  )
}
