// web/src/features/system/UsersPage.tsx
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Form, Input, Modal, Switch, Table, Tag } from 'antd'
import { useState } from 'react'

import { createUser, updateUser, updateUserPassword, updateUserStatus } from '@/api/users'
import type { User } from '@/api/types'
import { queryKeys } from '@/app/query-keys'
import { useAuth } from '@/auth/auth-state'
import { actionErrorMessage } from './errors'
import { useUsersQuery } from './queries'

type UserForm = {
  username: string
  display_name: string
  password: string
  is_system_admin: boolean
}

export default function UsersPage() {
  const { message, modal } = App.useApp()
  const { systemAdmin } = useAuth()
  const queryClient = useQueryClient()
  const users = useUsersQuery(systemAdmin)
  const [userForm] = Form.useForm<UserForm>()
  const [passwordForm] = Form.useForm<{ password: string }>()
  const [editing, setEditing] = useState<User | null>(null)
  const [passwordUser, setPasswordUser] = useState<User | null>(null)
  const [userOpen, setUserOpen] = useState(false)
  const [passwordOpen, setPasswordOpen] = useState(false)
  const [actionError, setActionError] = useState<unknown>(null)
  const refresh = () => queryClient.invalidateQueries({ queryKey: queryKeys.users })
  const save = useMutation({
    mutationFn: (values: UserForm) => editing
      ? updateUser(editing.id, { display_name: values.display_name, is_system_admin: values.is_system_admin, version: editing.version })
      : createUser(values),
    onSuccess: refresh,
  })
  const password = useMutation({
    mutationFn: (value: string) => {
      if (!passwordUser) throw new Error('没有选择用户')
      return updateUserPassword(passwordUser.id, value)
    },
  })
  const status = useMutation({
    mutationFn: (user: User) => updateUserStatus(user.id, !user.enabled, user.version),
    onSuccess: refresh,
  })

  const closeUser = () => {
    setUserOpen(false)
    setEditing(null)
    userForm.resetFields()
  }
  const showCreate = () => {
    setActionError(null)
    setEditing(null)
    userForm.setFieldsValue({ username: '', display_name: '', password: '', is_system_admin: false })
    setUserOpen(true)
  }
  const showEdit = (user: User) => {
    setActionError(null)
    setEditing(user)
    userForm.setFieldsValue({ username: user.username, display_name: user.display_name ?? '', password: '', is_system_admin: user.is_system_admin })
    setUserOpen(true)
  }
  const submitUser = async (values: UserForm) => {
    setActionError(null)
    try {
      await save.mutateAsync(values)
      closeUser()
      void message.success('用户已保存')
    } catch (error: unknown) {
      userForm.setFieldValue('password', '')
      setActionError(error)
    }
  }
  const submitPassword = async ({ password: nextPassword }: { password: string }) => {
    setActionError(null)
    try {
      await password.mutateAsync(nextPassword)
      setPasswordOpen(false)
      setPasswordUser(null)
      passwordForm.resetFields()
      void message.success('密码已更新')
    } catch (error: unknown) {
      passwordForm.resetFields()
      setActionError(error)
    }
  }
  const confirmStatus = (user: User) => modal.confirm({
    title: '确认用户状态',
    content: `确认${user.enabled ? '停用' : '启用'}用户“${user.display_name || user.username}”吗？`,
    okText: user.enabled ? '停用' : '启用',
    onOk: async () => {
      setActionError(null)
      try {
        await status.mutateAsync(user)
        void message.success('用户状态已更新')
      } catch (error: unknown) {
        setActionError(error)
        throw error
      }
    },
  })

  const error = actionError ?? users.error
  return (
    <section className="management-panel">
      <header className="management-header">
        <div><h2>系统用户</h2><p>用户状态和系统管理员标记是全局设置。</p></div>
        {systemAdmin ? <Button type="primary" onClick={showCreate}>新建用户</Button> : null}
      </header>
      {error ? <Alert className="management-alert" type="error" showIcon message={actionErrorMessage(error, actionError ? '执行用户操作' : '读取用户')} /> : null}
      {!systemAdmin ? <Alert type="warning" showIcon message="环境管理员不能修改全局用户状态" /> : (
        <Table<User> rowKey="id" loading={users.isLoading} dataSource={users.data ?? []} locale={{ emptyText: '暂无用户' }} pagination={false} scroll={{ x: 860 }} columns={[
          { title: 'ID', dataIndex: 'id', width: 90 },
          { title: '用户名', dataIndex: 'username', width: 170 },
          { title: '显示名称', dataIndex: 'display_name', width: 170 },
          { title: '身份', width: 130, render: (_, user) => user.is_system_admin ? <Tag color="blue">系统管理员</Tag> : '普通用户' },
          { title: '状态', width: 100, render: (_, user) => <Tag color={user.enabled ? 'green' : 'default'}>{user.enabled ? '启用' : '停用'}</Tag> },
          { title: '操作', width: 230, fixed: 'right', render: (_, user) => <div className="table-actions"><Button type="link" onClick={() => showEdit(user)}>编辑</Button><Button type="link" onClick={() => { setActionError(null); setPasswordUser(user); passwordForm.resetFields(); setPasswordOpen(true) }}>改密码</Button><Button type="link" onClick={() => confirmStatus(user)}>{user.enabled ? '停用' : '启用'}</Button></div> },
        ]} />
      )}
      <Modal title={editing ? '编辑用户' : '新建用户'} open={userOpen} width={520} confirmLoading={save.isPending} onCancel={closeUser} onOk={() => userForm.submit()} afterClose={() => userForm.resetFields()} destroyOnHidden>
        <Form form={userForm} layout="vertical" onFinish={submitUser} preserve={false}>
          <Form.Item label="用户名" name="username" rules={[{ required: true, message: '请输入用户名' }, { max: 128, message: '用户名不能超过 128 个字符' }]}><Input disabled={Boolean(editing)} autoComplete="off" /></Form.Item>
          <Form.Item label="显示名称" name="display_name" rules={[{ required: true, message: '请输入显示名称' }, { max: 128, message: '显示名称不能超过 128 个字符' }]}><Input /></Form.Item>
          {!editing ? <Form.Item label="初始密码" name="password" rules={[{ required: true, message: '请输入初始密码' }, { min: 12, message: '密码至少需要 12 个字符' }]}><Input.Password autoComplete="new-password" /></Form.Item> : null}
          <Form.Item label="系统管理员" name="is_system_admin" valuePropName="checked"><Switch /></Form.Item>
        </Form>
      </Modal>
      <Modal title="修改密码" open={passwordOpen} width={460} confirmLoading={password.isPending} okText="保存密码" onCancel={() => { setPasswordOpen(false); setPasswordUser(null); passwordForm.resetFields() }} onOk={() => passwordForm.submit()} afterClose={() => passwordForm.resetFields()} destroyOnHidden>
        <Form form={passwordForm} layout="vertical" onFinish={submitPassword} preserve={false}>
          <Form.Item label="新密码" name="password" rules={[{ required: true, message: '请输入新密码' }, { min: 12, message: '密码至少需要 12 个字符' }]}><Input.Password autoComplete="new-password" /></Form.Item>
        </Form>
      </Modal>
    </section>
  )
}

// web/src/features/system/UsersPage.vue
<template>
  <section class="management-card">
    <header class="management-card__header">
      <div>
        <h2>系统用户</h2>
        <p>用户状态和系统管理员标记是全局设置。</p>
      </div>
      <el-button
        v-if="systemAdmin"
        type="primary"
        @click="openCreate"
      >
        新建用户
      </el-button>
    </header>

    <el-alert
      v-if="errorMessage"
      class="management-card__alert"
      :title="errorMessage"
      type="error"
      :closable="false"
      show-icon
    />
    <el-alert
      v-if="!systemAdmin"
      title="环境管理员不能修改全局用户状态"
      type="warning"
      :closable="false"
      show-icon
    />

    <el-table
      v-else
      v-loading="loading"
      :data="users"
      empty-text="暂无用户"
    >
      <el-table-column
        prop="id"
        label="ID"
        width="90"
      />
      <el-table-column
        prop="username"
        label="用户名"
        min-width="150"
      />
      <el-table-column
        prop="display_name"
        label="显示名称"
        min-width="150"
      />
      <el-table-column
        label="身份"
        width="130"
      >
        <template #default="{ row }">
          <el-tag v-if="row.is_system_admin">
            系统管理员
          </el-tag>
          <span v-else>普通用户</span>
        </template>
      </el-table-column>
      <el-table-column
        label="状态"
        width="100"
      >
        <template #default="{ row }">
          <el-tag :type="row.enabled ? 'success' : 'info'">
            {{ row.enabled ? '启用' : '停用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column
        label="操作"
        width="250"
        fixed="right"
      >
        <template #default="{ row }">
          <el-button
            type="text"
            @click="openEdit(row)"
          >
            编辑
          </el-button>
          <el-button
            type="text"
            @click="openPassword(row)"
          >
            改密码
          </el-button>
          <el-button
            type="text"
            @click="toggleStatus(row)"
          >
            {{ row.enabled ? '停用' : '启用' }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      :title="editing ? '编辑用户' : '新建用户'"
      :visible.sync="userDialogVisible"
      width="520px"
      :close-on-click-modal="false"
    >
      <el-form
        ref="userForm"
        :model="form"
        :rules="userRules"
        label-position="top"
      >
        <el-form-item
          label="用户名"
          prop="username"
        >
          <el-input
            v-model.trim="form.username"
            :disabled="editing"
            autocomplete="off"
          />
        </el-form-item>
        <el-form-item
          label="显示名称"
          prop="display_name"
        >
          <el-input v-model.trim="form.display_name" />
        </el-form-item>
        <el-form-item
          v-if="!editing"
          label="初始密码"
          prop="password"
        >
          <el-input
            v-model="form.password"
            type="password"
            show-password
            autocomplete="new-password"
          />
        </el-form-item>
        <el-form-item label="系统管理员">
          <el-switch v-model="form.is_system_admin" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="closeUserDialog">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="saving"
          @click="saveUser"
        >
          保存
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      title="修改密码"
      :visible.sync="passwordDialogVisible"
      width="460px"
      :close-on-click-modal="false"
      @closed="clearPassword"
    >
      <el-form
        ref="passwordForm"
        :model="passwordForm"
        :rules="passwordRules"
        label-position="top"
      >
        <el-form-item
          label="新密码"
          prop="password"
        >
          <el-input
            v-model="passwordForm.password"
            type="password"
            show-password
            autocomplete="new-password"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="passwordDialogVisible = false">
          取消
        </el-button>
        <el-button
          type="primary"
          :loading="savingPassword"
          @click="savePassword"
        >
          保存密码
        </el-button>
      </template>
    </el-dialog>
  </section>
</template>

<script>
import {
  createUser,
  listUsers,
  updateUser,
  updateUserPassword,
  updateUserStatus,
} from '@/api/users'

import { actionErrorMessage, requireList } from './errors'

function emptyUserForm() {
  return {
    id: null,
    username: '',
    display_name: '',
    password: '',
    is_system_admin: false,
    version: 0,
  }
}

export default {
  name: 'UsersPage',

  data() {
    return {
      users: [],
      loading: false,
      saving: false,
      savingPassword: false,
      errorMessage: '',
      userDialogVisible: false,
      passwordDialogVisible: false,
      form: emptyUserForm(),
      passwordForm: { userId: null, password: '' },
      userRules: {
        username: [
          { required: true, message: '请输入用户名', trigger: 'blur' },
          { max: 128, message: '用户名不能超过 128 个字符', trigger: 'blur' },
        ],
        display_name: [
          { required: true, message: '请输入显示名称', trigger: 'blur' },
          { max: 128, message: '显示名称不能超过 128 个字符', trigger: 'blur' },
        ],
        password: [
          { required: true, message: '请输入初始密码', trigger: 'blur' },
          { min: 12, message: '密码至少需要 12 个字符', trigger: 'blur' },
        ],
      },
      passwordRules: {
        password: [
          { required: true, message: '请输入新密码', trigger: 'blur' },
          { min: 12, message: '密码至少需要 12 个字符', trigger: 'blur' },
        ],
      },
    }
  },

  computed: {
    systemAdmin() {
      return this.$store.getters['session/systemAdmin']
    },
    editing() {
      return this.form.id !== null
    },
  },

  created() {
    if (this.systemAdmin) {
      this.load()
    }
  },

  methods: {
    async load() {
      this.loading = true
      this.errorMessage = ''
      try {
        this.users = requireList(await listUsers(), 'user list')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '读取用户')
      } finally {
        this.loading = false
      }
    },
    openCreate() {
      this.form = emptyUserForm()
      this.errorMessage = ''
      this.userDialogVisible = true
      this.$nextTick(() => this.$refs.userForm?.clearValidate())
    },
    openEdit(user) {
      this.form = {
        id: user.id,
        username: user.username,
        display_name: user.display_name,
        password: '',
        is_system_admin: user.is_system_admin,
        version: user.version,
      }
      this.errorMessage = ''
      this.userDialogVisible = true
      this.$nextTick(() => this.$refs.userForm?.clearValidate())
    },
    closeUserDialog() {
      this.userDialogVisible = false
      this.form.password = ''
    },
    async saveUser() {
      await this.$refs.userForm.validate()
      this.saving = true
      this.errorMessage = ''
      try {
        if (this.editing) {
          await updateUser(this.form.id, {
            display_name: this.form.display_name,
            is_system_admin: this.form.is_system_admin,
            version: this.form.version,
          })
        } else {
          await createUser({
            username: this.form.username,
            display_name: this.form.display_name,
            password: this.form.password,
            is_system_admin: this.form.is_system_admin,
          })
        }
        this.closeUserDialog()
        await this.load()
        this.$message.success('用户已保存')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '保存用户')
      } finally {
        this.form.password = ''
        this.saving = false
      }
    },
    openPassword(user) {
      this.passwordForm = { userId: user.id, password: '' }
      this.errorMessage = ''
      this.passwordDialogVisible = true
      this.$nextTick(() => this.$refs.passwordForm?.clearValidate())
    },
    clearPassword() {
      this.passwordForm = { userId: null, password: '' }
    },
    async savePassword() {
      await this.$refs.passwordForm.validate()
      this.savingPassword = true
      this.errorMessage = ''
      try {
        await updateUserPassword(
          this.passwordForm.userId,
          this.passwordForm.password,
        )
        this.passwordDialogVisible = false
        this.$message.success('密码已更新')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '修改密码')
      } finally {
        this.passwordForm.password = ''
        this.savingPassword = false
      }
    },
    async toggleStatus(user) {
      try {
        await this.$confirm(
          `确认${user.enabled ? '停用' : '启用'}用户“${
            user.display_name || user.username
          }”吗？`,
          '确认用户状态',
          { type: 'warning' },
        )
      } catch (error) {
        if (error === 'cancel' || error === 'close') {
          return
        }
        throw error
      }
      this.errorMessage = ''
      try {
        await updateUserStatus(user.id, !user.enabled, user.version)
        await this.load()
        this.$message.success('用户状态已更新')
      } catch (error) {
        this.errorMessage = actionErrorMessage(error, '修改用户状态')
      }
    },
  },
}
</script>

<style scoped src="./management-card.css"></style>
