// web/src/layout/AppLayout.vue
<template>
  <div class="app-shell">
    <header class="app-shell__header">
      <router-link
        class="app-shell__brand"
        to="/"
      >
        Kirby
      </router-link>

      <div class="app-shell__actions">
        <router-link
          v-if="showAdministration"
          class="app-shell__admin-link"
          :to="{ name: 'system-home' }"
        >
          管理
        </router-link>
        <EnvironmentTag :environment="currentEnvironment" />
        <el-select
          v-if="environments.length"
          :value="currentEnvironmentId"
          :loading="switching"
          aria-label="当前环境"
          size="small"
          @change="switchEnvironment"
        >
          <el-option
            v-for="environment in environments"
            :key="String(environment.id)"
            :label="environment.name"
            :value="environment.id"
            :disabled="!environment.enabled"
          />
        </el-select>
        <span class="app-shell__user">{{ displayName }}</span>
        <el-button
          type="text"
          @click="logout"
        >
          退出
        </el-button>
      </div>
    </header>

    <main class="app-shell__content">
      <router-view />
    </main>
  </div>
</template>

<script>
import EnvironmentTag from '@/components/EnvironmentTag'

export default {
  name: 'AppLayout',

  components: {
    EnvironmentTag,
  },

  computed: {
    environments() {
      return this.$store.state.environment.available
    },
    currentEnvironmentId() {
      return this.$store.state.environment.currentId
    },
    currentEnvironment() {
      return this.$store.getters['environment/current']
    },
    switching() {
      return this.$store.state.environment.switching
    },
    displayName() {
      const user = this.$store.state.session.user
      return user?.display_name || user?.username || ''
    },
    showAdministration() {
      return (
        this.$store.getters['session/systemAdmin'] ||
        this.$store.getters['environment/hasPermission'](
          'environment:member:manage',
        )
      )
    },
  },

  methods: {
    async switchEnvironment(environmentId) {
      try {
        await this.$store.dispatch('environment/select', environmentId)
      } catch (error) {
        this.$message.error(error.message)
      }
    },
    async logout() {
      let failure = null
      try {
        await this.$store.dispatch('session/logout')
      } catch (error) {
        failure = error
      }
      await this.$router.replace({ name: 'login' })
      if (failure) {
        this.$message.error(`服务端退出失败：${failure.message}`)
      }
    },
  },
}
</script>

<style scoped>
.app-shell {
  min-height: 100vh;
  background: #f3f5f8;
}

.app-shell__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  min-height: 64px;
  padding: 0 24px;
  border-bottom: 1px solid #e5e7eb;
  background: #fff;
}

.app-shell__brand {
  color: #111827;
  font-size: 22px;
  font-weight: 700;
  text-decoration: none;
}

.app-shell__actions {
  display: flex;
  align-items: center;
  gap: 12px;
}

.app-shell__user {
  color: #4b5563;
  font-size: 14px;
}

.app-shell__admin-link {
  color: #2563eb;
  font-size: 14px;
  font-weight: 600;
  text-decoration: none;
}

.app-shell__content {
  padding: 32px;
}

</style>

// web/src/layout/AppLayout.tsx
import {
  LogoutOutlined,
  ProjectOutlined,
  SettingOutlined,
} from '@ant-design/icons'
import { Alert, Button, Select, Tooltip } from 'antd'
import { useState } from 'react'
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom'

import { getApiErrorMessage } from '@/api/errors'
import type { Identifier } from '@/api/types'
import { useAuth } from '@/auth/auth-state'
import { useEnvironment } from '@/auth/environment-state'
import EnvironmentTag from '@/components/EnvironmentTag/EnvironmentTag'

export default function AppLayout() {
  const auth = useAuth()
  const environment = useEnvironment()
  const location = useLocation()
  const navigate = useNavigate()
  const [failure, setFailure] = useState('')
  const showAdministration =
    auth.systemAdmin || environment.hasPermission('environment:member:manage')

  const switchEnvironment = async (environmentId: Identifier) => {
    setFailure('')
    try {
      await environment.select(environmentId)
      if (location.pathname !== '/projects') navigate('/projects', { replace: true })
    } catch (error: unknown) {
      setFailure(getApiErrorMessage(error, '环境切换失败'))
    }
  }

  const logout = async () => {
    let error: unknown = null
    try {
      await auth.logout()
    } catch (reason: unknown) {
      error = reason
    }
    navigate('/login', { replace: true })
    if (error) setFailure(`服务端退出失败：${getApiErrorMessage(error)}`)
  }

  return (
    <div className="app-shell">
      <header className="app-header">
        <Link className="app-brand" to="/">Kirby</Link>
        <nav className="app-navigation" aria-label="主导航">
          <Link to="/projects"><ProjectOutlined /> 项目</Link>
          {showAdministration ? <Link to="/system"><SettingOutlined /> 管理</Link> : null}
        </nav>
        <div className="app-actions">
          <EnvironmentTag environment={environment.current} />
          {environment.available.length ? (
            <Select
              aria-label="当前环境"
              value={environment.currentId}
              loading={environment.switching}
              options={environment.available.map((item) => ({
                label: item.name,
                value: item.id,
                disabled: !item.enabled,
              }))}
              onChange={(value) => void switchEnvironment(value)}
            />
          ) : null}
          <span className="app-user">{auth.user?.display_name || auth.user?.username}</span>
          <Tooltip title="退出">
            <Button aria-label="退出" type="text" icon={<LogoutOutlined />} onClick={() => void logout()} />
          </Tooltip>
        </div>
      </header>
      {failure ? <Alert className="shell-alert" type="error" showIcon closable message={failure} onClose={() => setFailure('')} /> : null}
      <main className="app-content"><Outlet /></main>
    </div>
  )
}
