// web/src/components/SchemaForm/SchemaForm.vue
<template>
  <FormProvider :form="form">
    <SchemaField
      :key="formKey"
      :schema="schema"
      :components="schemaComponents"
    />
  </FormProvider>
</template>

<script>
import { createForm } from '@formily/core'
import { createSchemaField, FormProvider } from '@formily/vue'

import {
  createWrappedSchema,
  normalizeData,
  unwrapValue,
  wrapValue,
} from '@/utils/schema/index.js'
import {
  ArrayCards,
  ArrayItems,
  DatePicker,
  FormItem,
  Input,
  InputNumber,
  Select,
  Space,
  Switch,
  TimePicker,
} from './formily-components.js'

const SchemaFields = createSchemaField({
  components: {
    ArrayCards,
    ArrayItems,
    DatePicker,
    FormItem,
    Input,
    InputNumber,
    Select,
    Space,
    Switch,
    TimePicker,
  },
})

const MissingFileUpload = {
  name: 'MissingFileUpload',
  created() {
    throw new Error('文件字段需要通过 fileUploadComponent 显式注入上传组件')
  },
  render(createElement) {
    return createElement('span')
  },
}

export default {
  name: 'SchemaForm',
  components: {
    FormProvider,
    ...SchemaFields,
  },
  props: {
    config: {
      type: Object,
      default: () => ({}),
    },
    value: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    models: {
      type: Array,
      default: () => [],
    },
    enums: {
      type: Array,
      default: () => [],
    },
    fileUploadComponent: {
      type: [Object, Function],
      default: null,
    },
  },
  data() {
    return {
      form: createForm(),
      formKey: 0,
      schema: {},
    }
  },
  computed: {
    resources() {
      return { models: this.models, enums: this.enums }
    },
    schemaComponents() {
      return {
        FileUpload: this.fileUploadComponent || MissingFileUpload,
      }
    },
  },
  watch: {
    config: {
      deep: true,
      immediate: true,
      handler() {
        this.rebuildSchema()
      },
    },
    models: {
      deep: true,
      handler() {
        this.rebuildSchema()
      },
    },
    enums: {
      deep: true,
      handler() {
        this.rebuildSchema()
      },
    },
    value: {
      immediate: true,
      handler(value) {
        this.setValue(value)
      },
    },
    disabled: {
      immediate: true,
      handler(disabled) {
        this.form.setPattern(disabled ? 'disabled' : 'editable')
      },
    },
  },
  methods: {
    rebuildSchema() {
      if (!this.config?.value) {
        this.schema = {}
        return
      }
      this.schema = createWrappedSchema(this.config, this.resources)
      this.form = createForm({ pattern: this.disabled ? 'disabled' : 'editable' })
      this.formKey += 1
      this.setValue(this.value)
    },
    getValue() {
      if (!this.config?.value) {
        return ''
      }
      const formValue = this.form.getFormState().values
      return unwrapValue(formValue, this.config.value)
    },
    setValue(value) {
      if (!this.config?.value) {
        return
      }
      const normalizedValue = normalizeData(this.config, value, this.resources)
      const wrappedValue = wrapValue(normalizedValue, this.config.value)
      this.form.setValues(wrappedValue, 'overwrite')
    },
  },
}
</script>

// web/src/components/SchemaForm/SchemaForm.tsx
import { createForm, type Form } from '@formily/core'
import type { ISchema } from '@formily/json-schema'
import { createSchemaField, FormProvider } from '@formily/react'
import {
  ArrayCards,
  ArrayItems,
  DatePicker,
  FormItem,
  Input,
  NumberPicker,
  Select,
  Space,
  Switch,
  TimePicker,
} from '@formily/antd-v5'
import {
  type ComponentType,
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
} from 'react'

import {
  createWrappedSchema,
  normalizeData,
  unwrapValue,
  wrapValue,
  type EnumResource,
  type ModelResource,
  type SchemaNode,
} from '@/domain/schema'

type FileFieldProps = {
  value?: string | string[]
  disabled?: boolean
  onChange?: (value: string | string[]) => void
  uploadType?: 'Image' | 'Video' | 'File'
  isArray?: boolean
}

export type SchemaFormHandle = {
  getValue: () => unknown
  setValue: (value: string) => void
  form: Form
}

export type SchemaFormProps = {
  config?: SchemaNode
  value?: string
  disabled?: boolean
  models?: ModelResource[]
  enums?: EnumResource[]
  fileUploadComponent?: ComponentType<FileFieldProps>
}

function MissingFileUpload(): never {
  throw new Error('文件字段需要通过 fileUploadComponent 显式注入上传组件')
}

const SchemaForm = forwardRef<SchemaFormHandle, SchemaFormProps>(
  function SchemaForm(
    {
      config,
      value = '',
      disabled = false,
      models = [],
      enums = [],
      fileUploadComponent = MissingFileUpload,
    },
    ref,
  ) {
    const resources = useMemo(() => ({ models, enums }), [enums, models])
    const schema = useMemo(
      () => config ? createWrappedSchema(config, resources) : {},
      [config, resources],
    )
    const form = useMemo(() => createForm(), [])
    const SchemaField = useMemo(
      () => createSchemaField({
        components: {
          ArrayCards,
          ArrayItems,
          DatePicker,
          FileUpload: fileUploadComponent,
          FormItem,
          Input,
          NumberPicker,
          Select,
          Space,
          Switch,
          TimePicker,
        },
      }),
      [fileUploadComponent],
    )

    const setValue = useCallback((serializedValue: string) => {
      if (!config) return
      const normalized = normalizeData(config, serializedValue, resources)
      form.setValues(wrapValue(normalized, config.value), 'overwrite')
    }, [config, form, resources])

    useEffect(() => {
      setValue(value)
    }, [setValue, value])

    useEffect(() => {
      form.setPattern(disabled ? 'disabled' : 'editable')
    }, [disabled, form])

    useImperativeHandle(ref, () => ({
      form,
      getValue: () => config
        ? unwrapValue(form.getFormState().values, config.value)
        : '',
      setValue,
    }), [config, form, setValue])

    if (!config) return null
    return (
      <FormProvider form={form}>
        <SchemaField schema={schema as ISchema} />
      </FormProvider>
    )
  },
)

export default SchemaForm
