// web/src/components/MonacoEditor/MonacoEditor.tsx
import { useEffect, useRef } from 'react'
import * as monaco from 'monaco-editor/editor/editor.api'
import 'monaco-editor/language/json/monaco.contribution'

import { configureMonacoWorkers } from './monaco-environment'

configureMonacoWorkers()

type Props = {
  value?: string
  disabled?: boolean
  language?: string
  onChange?: (value: string) => void
}

export default function MonacoEditor({
  value = '',
  disabled = false,
  language = 'json',
  onChange,
}: Props) {
  const container = useRef<HTMLDivElement | null>(null)
  const editor = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const onChangeRef = useRef(onChange)
  const initialValue = useRef(value)
  const initialLanguage = useRef(language)
  const initialDisabled = useRef(disabled)

  useEffect(() => {
    onChangeRef.current = onChange
  }, [onChange])

  useEffect(() => {
    if (!container.current) throw new Error('MonacoEditor container is missing')
    const instance = monaco.editor.create(container.current, {
      value: initialValue.current,
      language: initialLanguage.current,
      automaticLayout: true,
      minimap: { enabled: false },
      readOnly: initialDisabled.current,
    })
    editor.current = instance
    const subscription = instance.onDidChangeModelContent(() => {
      onChangeRef.current?.(instance.getValue())
    })
    return () => {
      subscription.dispose()
      instance.dispose()
      editor.current = null
    }
  }, [])

  useEffect(() => {
    const instance = editor.current
    if (instance && instance.getValue() !== value) instance.setValue(value)
  }, [value])

  useEffect(() => {
    editor.current?.updateOptions({ readOnly: disabled })
  }, [disabled])

  useEffect(() => {
    const model = editor.current?.getModel()
    if (model) monaco.editor.setModelLanguage(model, language)
  }, [language])

  return <div ref={container} className="monaco-editor-container" />
}

// web/src/components/MonacoEditor/MonacoEditor.vue
<template>
  <div
    ref="editorContainer"
    class="monaco-editor-container"
  />
</template>

<script>
import * as monaco from 'monaco-editor/editor/editor.api'
import 'monaco-editor/language/json/monaco.contribution'

import { configureMonacoWorkers } from './environment.js'

configureMonacoWorkers()

export default {
  name: 'MonacoEditor',
  props: {
    value: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    language: {
      type: String,
      default: 'json',
    },
  },
  data() {
    return {
      editor: null,
      changeSubscription: null,
    }
  },
  watch: {
    value(newValue) {
      this.setValue(newValue)
    },
    disabled(newValue) {
      this.editor?.updateOptions({ readOnly: newValue })
    },
  },
  mounted() {
    this.editor = monaco.editor.create(this.$refs.editorContainer, {
      value: this.value,
      language: this.language,
      automaticLayout: true,
      minimap: { enabled: false },
      readOnly: this.disabled,
    })
    this.changeSubscription = this.editor.onDidChangeModelContent(() => {
      const nextValue = this.editor.getValue()
      if (nextValue !== this.value) {
        this.$emit('input', nextValue)
        this.$emit('change', nextValue)
      }
    })
  },
  beforeDestroy() {
    this.changeSubscription?.dispose()
    this.editor?.dispose()
  },
  methods: {
    getValue() {
      return this.editor ? this.editor.getValue() : this.value
    },
    setValue(newValue) {
      if (typeof newValue !== 'string') {
        throw new TypeError('MonacoEditor 的 value 必须是字符串')
      }
      if (this.editor && this.editor.getValue() !== newValue) {
        this.editor.setValue(newValue)
      }
    },
  },
}
</script>

<style scoped>
.monaco-editor-container {
  width: 100%;
  min-height: 240px;
}
</style>
